/* config.c generated by valac 0.20.1, the Vala compiler
 * generated from config.vala, do not modify */

/*
 Copyright (C) 2014 Christian Dywan <christian@twotoasts.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>


#define ADBLOCK_TYPE_CONFIG (adblock_config_get_type ())
#define ADBLOCK_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_CONFIG, AdblockConfig))
#define ADBLOCK_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_CONFIG, AdblockConfigClass))
#define ADBLOCK_IS_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_CONFIG))
#define ADBLOCK_IS_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_CONFIG))
#define ADBLOCK_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_CONFIG, AdblockConfigClass))

typedef struct _AdblockConfig AdblockConfig;
typedef struct _AdblockConfigClass AdblockConfigClass;
typedef struct _AdblockConfigPrivate AdblockConfigPrivate;

#define ADBLOCK_TYPE_SUBSCRIPTION (adblock_subscription_get_type ())
#define ADBLOCK_SUBSCRIPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_SUBSCRIPTION, AdblockSubscription))
#define ADBLOCK_SUBSCRIPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_SUBSCRIPTION, AdblockSubscriptionClass))
#define ADBLOCK_IS_SUBSCRIPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_SUBSCRIPTION))
#define ADBLOCK_IS_SUBSCRIPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_SUBSCRIPTION))
#define ADBLOCK_SUBSCRIPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_SUBSCRIPTION, AdblockSubscriptionClass))

typedef struct _AdblockSubscription AdblockSubscription;
typedef struct _AdblockSubscriptionClass AdblockSubscriptionClass;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))

#define ADBLOCK_TYPE_FEATURE (adblock_feature_get_type ())
#define ADBLOCK_FEATURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_FEATURE, AdblockFeature))
#define ADBLOCK_FEATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_FEATURE, AdblockFeatureClass))
#define ADBLOCK_IS_FEATURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_FEATURE))
#define ADBLOCK_IS_FEATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_FEATURE))
#define ADBLOCK_FEATURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_FEATURE, AdblockFeatureClass))

typedef struct _AdblockFeature AdblockFeature;
typedef struct _AdblockFeatureClass AdblockFeatureClass;

#define ADBLOCK_TYPE_UPDATER (adblock_updater_get_type ())
#define ADBLOCK_UPDATER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_UPDATER, AdblockUpdater))
#define ADBLOCK_UPDATER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_UPDATER, AdblockUpdaterClass))
#define ADBLOCK_IS_UPDATER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_UPDATER))
#define ADBLOCK_IS_UPDATER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_UPDATER))
#define ADBLOCK_UPDATER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_UPDATER, AdblockUpdaterClass))

typedef struct _AdblockUpdater AdblockUpdater;
typedef struct _AdblockUpdaterClass AdblockUpdaterClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

struct _AdblockConfig {
	GObject parent_instance;
	AdblockConfigPrivate * priv;
};

struct _AdblockConfigClass {
	GObjectClass parent_class;
};

struct _AdblockConfigPrivate {
	GList* subscriptions;
	gchar* _path;
	GKeyFile* keyfile;
	gboolean should_save;
	gboolean _enabled;
	guint _size;
};


static gpointer adblock_config_parent_class = NULL;

GType adblock_config_get_type (void) G_GNUC_CONST;
GType adblock_subscription_get_type (void) G_GNUC_CONST;
#define ADBLOCK_CONFIG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ADBLOCK_TYPE_CONFIG, AdblockConfigPrivate))
enum  {
	ADBLOCK_CONFIG_DUMMY_PROPERTY,
	ADBLOCK_CONFIG_PATH,
	ADBLOCK_CONFIG_ENABLED,
	ADBLOCK_CONFIG_SIZE
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
AdblockConfig* adblock_config_new (const gchar* path, const gchar* presets);
AdblockConfig* adblock_config_construct (GType object_type, const gchar* path, const gchar* presets);
void adblock_config_set_enabled (AdblockConfig* self, gboolean value);
static void adblock_config_set_path (AdblockConfig* self, const gchar* value);
static void adblock_config_set_size (AdblockConfig* self, guint value);
static void adblock_config_load_file (AdblockConfig* self, const gchar* filename);
AdblockSubscription* adblock_subscription_new (const gchar* uri);
AdblockSubscription* adblock_subscription_construct (GType object_type, const gchar* uri);
void adblock_subscription_set_active (AdblockSubscription* self, gboolean value);
GType adblock_feature_get_type (void) G_GNUC_CONST;
void adblock_subscription_add_feature (AdblockSubscription* self, AdblockFeature* feature);
AdblockUpdater* adblock_updater_new (void);
AdblockUpdater* adblock_updater_construct (GType object_type);
GType adblock_updater_get_type (void) G_GNUC_CONST;
gboolean adblock_config_add (AdblockConfig* self, AdblockSubscription* sub);
static void adblock_config_enabled_changed (AdblockConfig* self, GParamSpec* pspec);
static void _adblock_config_enabled_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean adblock_config_get_enabled (AdblockConfig* self);
void adblock_config_save (AdblockConfig* self);
static void adblock_config_active_changed (AdblockConfig* self, GObject* subscription, GParamSpec* pspec);
static void adblock_config_update_filters (AdblockConfig* self);
gboolean adblock_subscription_get_mutable (AdblockSubscription* self);
const gchar* adblock_subscription_get_uri (AdblockSubscription* self);
gboolean adblock_subscription_get_active (AdblockSubscription* self);
const gchar* adblock_config_get_path (AdblockConfig* self);
AdblockSubscription* adblock_config_get (AdblockConfig* self, guint index);
static gboolean adblock_config_contains (AdblockConfig* self, AdblockSubscription* subscription);
static void _adblock_config_active_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
guint adblock_config_get_size (AdblockConfig* self);
void adblock_config_remove (AdblockConfig* self, AdblockSubscription* sub);
static void adblock_config_finalize (GObject* obj);
static void _vala_adblock_config_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_adblock_config_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _g_object_unref0_ (gpointer var) {
#line 14 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 143 "config.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 14 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 14 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_list_free (self);
#line 152 "config.c"
}


AdblockConfig* adblock_config_construct (GType object_type, const gchar* path, const gchar* presets) {
	AdblockConfig * self = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
#line 20 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self = (AdblockConfig*) g_object_new (object_type, NULL);
#line 21 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->should_save = FALSE;
#line 22 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	__g_list_free__g_object_unref0_0 (self->priv->subscriptions);
#line 22 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->subscriptions = NULL;
#line 23 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_set_enabled (self, TRUE);
#line 24 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = path;
#line 24 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_set_path (self, _tmp0_);
#line 25 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_set_size (self, (guint) 0);
#line 26 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp1_ = path;
#line 26 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_load_file (self, _tmp1_);
#line 27 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp2_ = presets;
#line 27 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_load_file (self, _tmp2_);
#line 28 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->should_save = TRUE;
#line 20 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return self;
#line 189 "config.c"
}


AdblockConfig* adblock_config_new (const gchar* path, const gchar* presets) {
#line 20 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return adblock_config_construct (ADBLOCK_TYPE_CONFIG, path, presets);
#line 196 "config.c"
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* end;
	gchar* _tmp3_;
#line 1157 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp0_ = str;
#line 1157 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp1_ = maxlen;
#line 1157 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
#line 1157 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	end = _tmp2_;
#line 1158 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp3_ = end;
#line 1158 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp3_ == NULL) {
#line 219 "config.c"
		glong _tmp4_;
#line 1159 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp4_ = maxlen;
#line 1159 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		result = _tmp4_;
#line 1159 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		return result;
#line 227 "config.c"
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
#line 1161 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp5_ = end;
#line 1161 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp6_ = str;
#line 1161 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		result = (glong) (_tmp5_ - _tmp6_);
#line 1161 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		return result;
#line 239 "config.c"
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	gboolean _tmp3_;
	glong _tmp9_;
	glong _tmp15_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
#line 1168 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp1_ = offset;
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp1_ >= ((glong) 0)) {
#line 264 "config.c"
		glong _tmp2_;
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp2_ = len;
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp0_ = _tmp2_ >= ((glong) 0);
#line 270 "config.c"
	} else {
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 274 "config.c"
	}
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp3_ = _tmp0_;
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp3_) {
#line 280 "config.c"
		glong _tmp4_;
		glong _tmp5_;
		glong _tmp6_ = 0L;
#line 1172 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp4_ = offset;
#line 1172 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp5_ = len;
#line 1172 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
#line 1172 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		string_length = _tmp6_;
#line 292 "config.c"
	} else {
		gint _tmp7_;
		gint _tmp8_;
#line 1174 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp7_ = strlen (self);
#line 1174 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp8_ = _tmp7_;
#line 1174 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		string_length = (glong) _tmp8_;
#line 302 "config.c"
	}
#line 1177 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp9_ = offset;
#line 1177 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp9_ < ((glong) 0)) {
#line 308 "config.c"
		glong _tmp10_;
		glong _tmp11_;
		glong _tmp12_;
#line 1178 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp10_ = string_length;
#line 1178 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp11_ = offset;
#line 1178 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		offset = _tmp10_ + _tmp11_;
#line 1179 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp12_ = offset;
#line 1179 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
#line 322 "config.c"
	} else {
		glong _tmp13_;
		glong _tmp14_;
#line 1181 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp13_ = offset;
#line 1181 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp14_ = string_length;
#line 1181 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
#line 332 "config.c"
	}
#line 1183 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp15_ = len;
#line 1183 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp15_ < ((glong) 0)) {
#line 338 "config.c"
		glong _tmp16_;
		glong _tmp17_;
#line 1184 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp16_ = string_length;
#line 1184 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp17_ = offset;
#line 1184 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		len = _tmp16_ - _tmp17_;
#line 347 "config.c"
	}
#line 1186 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp18_ = offset;
#line 1186 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp19_ = len;
#line 1186 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp20_ = string_length;
#line 1186 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp21_ = offset;
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp22_ = len;
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	result = _tmp23_;
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	return result;
#line 367 "config.c"
}


static void _adblock_config_enabled_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 66 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_enabled_changed (self, pspec);
#line 374 "config.c"
}


static void adblock_config_load_file (AdblockConfig* self, const gchar* filename) {
	const gchar* _tmp0_;
	GKeyFile* _tmp1_;
	GError * _inner_error_ = NULL;
#line 31 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 32 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = filename;
#line 32 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	if (_tmp0_ == NULL) {
#line 33 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		return;
#line 390 "config.c"
	}
#line 35 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp1_ = g_key_file_new ();
#line 35 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_g_key_file_free0 (self->priv->keyfile);
#line 35 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->keyfile = _tmp1_;
#line 398 "config.c"
	{
		GKeyFile* _tmp2_;
		const gchar* _tmp3_;
		GKeyFile* _tmp4_;
		gsize _tmp5_;
		gchar** _tmp6_ = NULL;
		gchar** filters;
		gint filters_length1;
		gint _filters_size_;
		gchar** _tmp7_;
		gint _tmp7__length1;
		GKeyFile* _tmp37_;
		gboolean _tmp38_ = FALSE;
		gboolean _tmp39_;
#line 37 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp2_ = self->priv->keyfile;
#line 37 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp3_ = filename;
#line 37 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_key_file_load_from_file (_tmp2_, _tmp3_, G_KEY_FILE_NONE, &_inner_error_);
#line 37 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		if (_inner_error_ != NULL) {
#line 37 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_KEY_FILE_ERROR, G_KEY_FILE_ERROR_KEY_NOT_FOUND)) {
#line 423 "config.c"
				goto __catch17_g_key_file_error_key_not_found;
			}
#line 37 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_KEY_FILE_ERROR, G_KEY_FILE_ERROR_GROUP_NOT_FOUND)) {
#line 428 "config.c"
				goto __catch17_g_key_file_error_group_not_found;
			}
#line 37 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_FILE_ERROR, G_FILE_ERROR_NOENT)) {
#line 433 "config.c"
				goto __catch17_g_file_error_noent;
			}
			goto __catch17_g_error;
		}
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp4_ = self->priv->keyfile;
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp6_ = g_key_file_get_string_list (_tmp4_, "settings", "filters", &_tmp5_, &_inner_error_);
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		filters = _tmp6_;
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		filters_length1 = _tmp5_;
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_filters_size_ = filters_length1;
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		if (_inner_error_ != NULL) {
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_KEY_FILE_ERROR, G_KEY_FILE_ERROR_KEY_NOT_FOUND)) {
#line 452 "config.c"
				goto __catch17_g_key_file_error_key_not_found;
			}
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_KEY_FILE_ERROR, G_KEY_FILE_ERROR_GROUP_NOT_FOUND)) {
#line 457 "config.c"
				goto __catch17_g_key_file_error_group_not_found;
			}
#line 38 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_FILE_ERROR, G_FILE_ERROR_NOENT)) {
#line 462 "config.c"
				goto __catch17_g_file_error_noent;
			}
			goto __catch17_g_error;
		}
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp7_ = filters;
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp7__length1 = filters_length1;
#line 471 "config.c"
		{
			gchar** filter_collection = NULL;
			gint filter_collection_length1 = 0;
			gint _filter_collection_size_ = 0;
			gint filter_it = 0;
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			filter_collection = _tmp7_;
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			filter_collection_length1 = _tmp7__length1;
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			for (filter_it = 0; filter_it < _tmp7__length1; filter_it = filter_it + 1) {
#line 483 "config.c"
				gchar* _tmp8_;
				gchar* filter = NULL;
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp8_ = g_strdup (filter_collection[filter_it]);
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				filter = _tmp8_;
#line 490 "config.c"
				{
					gboolean active;
					const gchar* _tmp9_;
					gchar* _tmp10_;
					gchar* uri;
					const gchar* _tmp11_;
					gboolean _tmp12_ = FALSE;
					const gchar* _tmp29_;
					AdblockSubscription* _tmp30_;
					AdblockSubscription* sub;
					AdblockSubscription* _tmp31_;
					gboolean _tmp32_;
					AdblockSubscription* _tmp33_;
					AdblockUpdater* _tmp34_;
					AdblockUpdater* _tmp35_;
					AdblockSubscription* _tmp36_;
#line 40 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					active = FALSE;
#line 41 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp9_ = filter;
#line 41 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp10_ = g_strdup (_tmp9_);
#line 41 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					uri = _tmp10_;
#line 42 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp11_ = filter;
#line 42 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp12_ = g_str_has_prefix (_tmp11_, "http-/");
#line 42 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					if (_tmp12_) {
#line 521 "config.c"
						const gchar* _tmp13_;
						gchar* _tmp14_ = NULL;
						gchar* _tmp15_;
						gchar* _tmp16_;
#line 43 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp13_ = filter;
#line 43 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp14_ = string_substring (_tmp13_, (glong) 5, (glong) (-1));
#line 43 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp15_ = _tmp14_;
#line 43 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp16_ = g_strconcat ("http:", _tmp15_, NULL);
#line 43 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_g_free0 (uri);
#line 43 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						uri = _tmp16_;
#line 43 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_g_free0 (_tmp15_);
#line 540 "config.c"
					} else {
						const gchar* _tmp17_;
						gboolean _tmp18_ = FALSE;
#line 44 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp17_ = filter;
#line 44 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp18_ = g_str_has_prefix (_tmp17_, "file-/");
#line 44 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						if (_tmp18_) {
#line 550 "config.c"
							const gchar* _tmp19_;
							gchar* _tmp20_ = NULL;
							gchar* _tmp21_;
							gchar* _tmp22_;
#line 45 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp19_ = filter;
#line 45 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp20_ = string_substring (_tmp19_, (glong) 5, (glong) (-1));
#line 45 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp21_ = _tmp20_;
#line 45 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp22_ = g_strconcat ("file:", _tmp21_, NULL);
#line 45 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_g_free0 (uri);
#line 45 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							uri = _tmp22_;
#line 45 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_g_free0 (_tmp21_);
#line 569 "config.c"
						} else {
							const gchar* _tmp23_;
							gboolean _tmp24_ = FALSE;
#line 46 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp23_ = filter;
#line 46 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp24_ = g_str_has_prefix (_tmp23_, "http-:");
#line 46 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							if (_tmp24_) {
#line 579 "config.c"
								const gchar* _tmp25_;
								gchar* _tmp26_ = NULL;
								gchar* _tmp27_;
								gchar* _tmp28_;
#line 47 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
								_tmp25_ = filter;
#line 47 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
								_tmp26_ = string_substring (_tmp25_, (glong) 5, (glong) (-1));
#line 47 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
								_tmp27_ = _tmp26_;
#line 47 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
								_tmp28_ = g_strconcat ("https", _tmp27_, NULL);
#line 47 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
								_g_free0 (uri);
#line 47 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
								uri = _tmp28_;
#line 47 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
								_g_free0 (_tmp27_);
#line 598 "config.c"
							} else {
#line 49 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
								active = TRUE;
#line 602 "config.c"
							}
						}
					}
#line 50 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp29_ = uri;
#line 50 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp30_ = adblock_subscription_new (_tmp29_);
#line 50 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					sub = _tmp30_;
#line 51 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp31_ = sub;
#line 51 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp32_ = active;
#line 51 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					adblock_subscription_set_active (_tmp31_, _tmp32_);
#line 52 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp33_ = sub;
#line 52 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp34_ = adblock_updater_new ();
#line 52 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp35_ = _tmp34_;
#line 52 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					adblock_subscription_add_feature (_tmp33_, (AdblockFeature*) _tmp35_);
#line 52 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_g_object_unref0 (_tmp35_);
#line 53 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp36_ = sub;
#line 53 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					adblock_config_add (self, _tmp36_);
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_g_object_unref0 (sub);
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_g_free0 (uri);
#line 39 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_g_free0 (filter);
#line 638 "config.c"
				}
			}
		}
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp37_ = self->priv->keyfile;
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp38_ = g_key_file_get_boolean (_tmp37_, "settings", "disabled", &_inner_error_);
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp39_ = _tmp38_;
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		if (_inner_error_ != NULL) {
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			filters = (_vala_array_free (filters, filters_length1, (GDestroyNotify) g_free), NULL);
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_KEY_FILE_ERROR, G_KEY_FILE_ERROR_KEY_NOT_FOUND)) {
#line 654 "config.c"
				goto __catch17_g_key_file_error_key_not_found;
			}
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_KEY_FILE_ERROR, G_KEY_FILE_ERROR_GROUP_NOT_FOUND)) {
#line 659 "config.c"
				goto __catch17_g_key_file_error_group_not_found;
			}
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			if (g_error_matches (_inner_error_, G_FILE_ERROR, G_FILE_ERROR_NOENT)) {
#line 664 "config.c"
				goto __catch17_g_file_error_noent;
			}
			goto __catch17_g_error;
		}
#line 55 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		adblock_config_set_enabled (self, !_tmp39_);
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		filters = (_vala_array_free (filters, filters_length1, (GDestroyNotify) g_free), NULL);
#line 673 "config.c"
	}
	goto __finally17;
	__catch17_g_key_file_error_key_not_found:
	{
		GError* key_error = NULL;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		key_error = _inner_error_;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_inner_error_ = NULL;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_g_error_free0 (key_error);
#line 685 "config.c"
	}
	goto __finally17;
	__catch17_g_key_file_error_group_not_found:
	{
		GError* group_error = NULL;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		group_error = _inner_error_;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_inner_error_ = NULL;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_g_error_free0 (group_error);
#line 697 "config.c"
	}
	goto __finally17;
	__catch17_g_file_error_noent:
	{
		GError* exist_error = NULL;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		exist_error = _inner_error_;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_inner_error_ = NULL;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_g_error_free0 (exist_error);
#line 709 "config.c"
	}
	goto __finally17;
	__catch17_g_error:
	{
		GError* settings_error = NULL;
		const gchar* _tmp40_;
		GError* _tmp41_;
		const gchar* _tmp42_;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		settings_error = _inner_error_;
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_inner_error_ = NULL;
#line 63 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp40_ = filename;
#line 63 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp41_ = settings_error;
#line 63 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp42_ = _tmp41_->message;
#line 63 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_warning ("config.vala:63: Error reading settings from %s: %s\n", _tmp40_, _tmp42_);
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_g_error_free0 (settings_error);
#line 732 "config.c"
	}
	__finally17:
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	if (_inner_error_ != NULL) {
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_clear_error (&_inner_error_);
#line 36 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		return;
#line 743 "config.c"
	}
#line 66 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_signal_connect_object ((GObject*) self, "notify::enabled", (GCallback) _adblock_config_enabled_changed_g_object_notify, self, 0);
#line 747 "config.c"
}


static void adblock_config_enabled_changed (AdblockConfig* self, GParamSpec* pspec) {
	GKeyFile* _tmp0_;
	gboolean _tmp1_;
#line 69 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 69 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (pspec != NULL);
#line 70 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = self->priv->keyfile;
#line 70 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp1_ = self->priv->_enabled;
#line 70 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_key_file_set_boolean (_tmp0_, "settings", "disabled", !_tmp1_);
#line 71 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_save (self);
#line 766 "config.c"
}


static void adblock_config_active_changed (AdblockConfig* self, GObject* subscription, GParamSpec* pspec) {
#line 74 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 74 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (subscription != NULL);
#line 74 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (pspec != NULL);
#line 75 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_update_filters (self);
#line 779 "config.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 80 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return self ? g_object_ref (self) : NULL;
#line 786 "config.c"
}


static void adblock_config_update_filters (AdblockConfig* self) {
	GString* _tmp0_;
	GString* filters;
	GList* _tmp1_;
	GString* _tmp62_;
	const gchar* _tmp63_;
	gboolean _tmp64_ = FALSE;
	GString* _tmp68_;
	const gchar* _tmp69_;
	gchar** _tmp70_;
	gchar** _tmp71_ = NULL;
	gchar** list;
	gint list_length1;
	gint _list_size_;
	GKeyFile* _tmp72_;
#line 78 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 79 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = g_string_new ("");
#line 79 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	filters = _tmp0_;
#line 80 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp1_ = self->priv->subscriptions;
#line 813 "config.c"
	{
		GList* sub_collection = NULL;
		GList* sub_it = NULL;
#line 80 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		sub_collection = _tmp1_;
#line 80 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		for (sub_it = sub_collection; sub_it != NULL; sub_it = sub_it->next) {
#line 821 "config.c"
			AdblockSubscription* _tmp2_;
			AdblockSubscription* sub = NULL;
#line 80 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			_tmp2_ = _g_object_ref0 ((AdblockSubscription*) sub_it->data);
#line 80 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			sub = _tmp2_;
#line 828 "config.c"
			{
				AdblockSubscription* _tmp3_;
				gboolean _tmp4_;
				gboolean _tmp5_;
				gboolean _tmp6_ = FALSE;
				AdblockSubscription* _tmp7_;
				const gchar* _tmp8_;
				const gchar* _tmp9_;
				gboolean _tmp10_ = FALSE;
				gboolean _tmp14_;
				GString* _tmp61_;
#line 81 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp3_ = sub;
#line 81 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp4_ = adblock_subscription_get_mutable (_tmp3_);
#line 81 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp5_ = _tmp4_;
#line 81 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				if (!_tmp5_) {
#line 82 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_g_object_unref0 (sub);
#line 82 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					continue;
#line 852 "config.c"
				}
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp7_ = sub;
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp8_ = adblock_subscription_get_uri (_tmp7_);
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp9_ = _tmp8_;
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp10_ = g_str_has_prefix (_tmp9_, "http:");
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				if (_tmp10_) {
#line 864 "config.c"
					AdblockSubscription* _tmp11_;
					gboolean _tmp12_;
					gboolean _tmp13_;
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp11_ = sub;
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp12_ = adblock_subscription_get_active (_tmp11_);
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp13_ = _tmp12_;
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp6_ = !_tmp13_;
#line 876 "config.c"
				} else {
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp6_ = FALSE;
#line 880 "config.c"
				}
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp14_ = _tmp6_;
#line 83 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				if (_tmp14_) {
#line 886 "config.c"
					GString* _tmp15_;
					AdblockSubscription* _tmp16_;
					const gchar* _tmp17_;
					const gchar* _tmp18_;
					gchar* _tmp19_ = NULL;
					gchar* _tmp20_;
					gchar* _tmp21_;
					gchar* _tmp22_;
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp15_ = filters;
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp16_ = sub;
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp17_ = adblock_subscription_get_uri (_tmp16_);
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp18_ = _tmp17_;
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp19_ = string_substring (_tmp18_, (glong) 4, (glong) (-1));
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp20_ = _tmp19_;
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp21_ = g_strconcat ("http-", _tmp20_, NULL);
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp22_ = _tmp21_;
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					g_string_append (_tmp15_, _tmp22_);
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_g_free0 (_tmp22_);
#line 84 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_g_free0 (_tmp20_);
#line 917 "config.c"
				} else {
					gboolean _tmp23_ = FALSE;
					AdblockSubscription* _tmp24_;
					const gchar* _tmp25_;
					const gchar* _tmp26_;
					gboolean _tmp27_ = FALSE;
					gboolean _tmp31_;
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp24_ = sub;
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp25_ = adblock_subscription_get_uri (_tmp24_);
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp26_ = _tmp25_;
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp27_ = g_str_has_prefix (_tmp26_, "file:");
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					if (_tmp27_) {
#line 935 "config.c"
						AdblockSubscription* _tmp28_;
						gboolean _tmp29_;
						gboolean _tmp30_;
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp28_ = sub;
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp29_ = adblock_subscription_get_active (_tmp28_);
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp30_ = _tmp29_;
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp23_ = !_tmp30_;
#line 947 "config.c"
					} else {
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp23_ = FALSE;
#line 951 "config.c"
					}
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_tmp31_ = _tmp23_;
#line 85 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					if (_tmp31_) {
#line 957 "config.c"
						GString* _tmp32_;
						AdblockSubscription* _tmp33_;
						const gchar* _tmp34_;
						const gchar* _tmp35_;
						gchar* _tmp36_ = NULL;
						gchar* _tmp37_;
						gchar* _tmp38_;
						gchar* _tmp39_;
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp32_ = filters;
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp33_ = sub;
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp34_ = adblock_subscription_get_uri (_tmp33_);
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp35_ = _tmp34_;
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp36_ = string_substring (_tmp35_, (glong) 5, (glong) (-1));
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp37_ = _tmp36_;
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp38_ = g_strconcat ("file-", _tmp37_, NULL);
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp39_ = _tmp38_;
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						g_string_append (_tmp32_, _tmp39_);
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_g_free0 (_tmp39_);
#line 86 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_g_free0 (_tmp37_);
#line 988 "config.c"
					} else {
						gboolean _tmp40_ = FALSE;
						AdblockSubscription* _tmp41_;
						const gchar* _tmp42_;
						const gchar* _tmp43_;
						gboolean _tmp44_ = FALSE;
						gboolean _tmp48_;
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp41_ = sub;
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp42_ = adblock_subscription_get_uri (_tmp41_);
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp43_ = _tmp42_;
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp44_ = g_str_has_prefix (_tmp43_, "https:");
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						if (_tmp44_) {
#line 1006 "config.c"
							AdblockSubscription* _tmp45_;
							gboolean _tmp46_;
							gboolean _tmp47_;
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp45_ = sub;
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp46_ = adblock_subscription_get_active (_tmp45_);
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp47_ = _tmp46_;
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp40_ = !_tmp47_;
#line 1018 "config.c"
						} else {
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp40_ = FALSE;
#line 1022 "config.c"
						}
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						_tmp48_ = _tmp40_;
#line 87 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
						if (_tmp48_) {
#line 1028 "config.c"
							GString* _tmp49_;
							AdblockSubscription* _tmp50_;
							const gchar* _tmp51_;
							const gchar* _tmp52_;
							gchar* _tmp53_ = NULL;
							gchar* _tmp54_;
							gchar* _tmp55_;
							gchar* _tmp56_;
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp49_ = filters;
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp50_ = sub;
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp51_ = adblock_subscription_get_uri (_tmp50_);
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp52_ = _tmp51_;
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp53_ = string_substring (_tmp52_, (glong) 5, (glong) (-1));
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp54_ = _tmp53_;
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp55_ = g_strconcat ("http-", _tmp54_, NULL);
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp56_ = _tmp55_;
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							g_string_append (_tmp49_, _tmp56_);
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_g_free0 (_tmp56_);
#line 88 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_g_free0 (_tmp54_);
#line 1059 "config.c"
						} else {
							GString* _tmp57_;
							AdblockSubscription* _tmp58_;
							const gchar* _tmp59_;
							const gchar* _tmp60_;
#line 90 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp57_ = filters;
#line 90 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp58_ = sub;
#line 90 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp59_ = adblock_subscription_get_uri (_tmp58_);
#line 90 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							_tmp60_ = _tmp59_;
#line 90 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
							g_string_append (_tmp57_, _tmp60_);
#line 1075 "config.c"
						}
					}
				}
#line 91 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp61_ = filters;
#line 91 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				g_string_append_c (_tmp61_, ';');
#line 80 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_g_object_unref0 (sub);
#line 1085 "config.c"
			}
		}
	}
#line 94 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp62_ = filters;
#line 94 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp63_ = _tmp62_->str;
#line 94 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp64_ = g_str_has_suffix (_tmp63_, ";");
#line 94 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	if (_tmp64_) {
#line 1097 "config.c"
		GString* _tmp65_;
		GString* _tmp66_;
		gssize _tmp67_;
#line 95 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp65_ = filters;
#line 95 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp66_ = filters;
#line 95 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp67_ = _tmp66_->len;
#line 95 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_string_truncate (_tmp65_, (gsize) (_tmp67_ - 1));
#line 1109 "config.c"
	}
#line 96 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp68_ = filters;
#line 96 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp69_ = _tmp68_->str;
#line 96 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp71_ = _tmp70_ = g_strsplit (_tmp69_, ";", 0);
#line 96 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	list = _tmp71_;
#line 96 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	list_length1 = _vala_array_length (_tmp70_);
#line 96 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_list_size_ = list_length1;
#line 97 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp72_ = self->priv->keyfile;
#line 97 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_key_file_set_string_list (_tmp72_, "settings", "filters", (const gchar* const*) list, list_length1);
#line 99 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_save (self);
#line 78 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	list = (_vala_array_free (list, list_length1, (GDestroyNotify) g_free), NULL);
#line 78 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_g_string_free0 (filters);
#line 1133 "config.c"
}


void adblock_config_save (AdblockConfig* self) {
	GError * _inner_error_ = NULL;
#line 103 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 1141 "config.c"
	{
		const gchar* _tmp0_;
		GKeyFile* _tmp1_;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_;
#line 105 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp0_ = self->priv->_path;
#line 105 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp1_ = self->priv->keyfile;
#line 105 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp2_ = g_key_file_to_data (_tmp1_, NULL, NULL);
#line 105 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp3_ = _tmp2_;
#line 105 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_file_set_contents (_tmp0_, _tmp3_, (gssize) (-1), &_inner_error_);
#line 105 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_g_free0 (_tmp3_);
#line 105 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		if (_inner_error_ != NULL) {
#line 1161 "config.c"
			goto __catch18_g_error;
		}
	}
	goto __finally18;
	__catch18_g_error:
	{
		GError* _error_ = NULL;
		GError* _tmp4_;
		const gchar* _tmp5_;
#line 104 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_error_ = _inner_error_;
#line 104 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_inner_error_ = NULL;
#line 107 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp4_ = _error_;
#line 107 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_tmp5_ = _tmp4_->message;
#line 107 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_warning ("config.vala:107: Failed to save settings: %s", _tmp5_);
#line 104 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		_g_error_free0 (_error_);
#line 1183 "config.c"
	}
	__finally18:
#line 104 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	if (_inner_error_ != NULL) {
#line 104 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 104 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_clear_error (&_inner_error_);
#line 104 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		return;
#line 1194 "config.c"
	}
}


AdblockSubscription* adblock_config_get (AdblockConfig* self, guint index) {
	AdblockSubscription* result = NULL;
	GList* _tmp0_;
	guint _tmp1_;
	gconstpointer _tmp2_ = NULL;
	AdblockSubscription* _tmp3_;
#line 112 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 113 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = self->priv->subscriptions;
#line 113 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp1_ = index;
#line 113 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp2_ = g_list_nth_data (_tmp0_, _tmp1_);
#line 113 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp3_ = _g_object_ref0 ((AdblockSubscription*) _tmp2_);
#line 113 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	result = _tmp3_;
#line 113 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return result;
#line 1219 "config.c"
}


static gboolean adblock_config_contains (AdblockConfig* self, AdblockSubscription* subscription) {
	gboolean result = FALSE;
	GList* _tmp0_;
#line 117 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 117 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_val_if_fail (subscription != NULL, FALSE);
#line 118 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = self->priv->subscriptions;
#line 1232 "config.c"
	{
		GList* sub_collection = NULL;
		GList* sub_it = NULL;
#line 118 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		sub_collection = _tmp0_;
#line 118 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		for (sub_it = sub_collection; sub_it != NULL; sub_it = sub_it->next) {
#line 1240 "config.c"
			AdblockSubscription* _tmp1_;
			AdblockSubscription* sub = NULL;
#line 118 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			_tmp1_ = _g_object_ref0 ((AdblockSubscription*) sub_it->data);
#line 118 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
			sub = _tmp1_;
#line 1247 "config.c"
			{
				AdblockSubscription* _tmp2_;
				const gchar* _tmp3_;
				const gchar* _tmp4_;
				AdblockSubscription* _tmp5_;
				const gchar* _tmp6_;
				const gchar* _tmp7_;
#line 119 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp2_ = sub;
#line 119 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp3_ = adblock_subscription_get_uri (_tmp2_);
#line 119 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp4_ = _tmp3_;
#line 119 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp5_ = subscription;
#line 119 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp6_ = adblock_subscription_get_uri (_tmp5_);
#line 119 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_tmp7_ = _tmp6_;
#line 119 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				if (g_strcmp0 (_tmp4_, _tmp7_) == 0) {
#line 120 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					result = TRUE;
#line 120 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					_g_object_unref0 (sub);
#line 120 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
					return result;
#line 1275 "config.c"
				}
#line 118 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
				_g_object_unref0 (sub);
#line 1279 "config.c"
			}
		}
	}
#line 121 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	result = FALSE;
#line 121 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return result;
#line 1287 "config.c"
}


static void _adblock_config_active_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 128 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_active_changed (self, _sender, pspec);
#line 1294 "config.c"
}


gboolean adblock_config_add (AdblockConfig* self, AdblockSubscription* sub) {
	gboolean result = FALSE;
	AdblockSubscription* _tmp0_;
	gboolean _tmp1_ = FALSE;
	AdblockSubscription* _tmp2_;
	AdblockSubscription* _tmp3_;
	AdblockSubscription* _tmp4_;
	guint _tmp5_;
	gboolean _tmp6_;
#line 124 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 124 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_val_if_fail (sub != NULL, FALSE);
#line 125 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = sub;
#line 125 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp1_ = adblock_config_contains (self, _tmp0_);
#line 125 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	if (_tmp1_) {
#line 126 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		result = FALSE;
#line 126 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		return result;
#line 1321 "config.c"
	}
#line 128 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp2_ = sub;
#line 128 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_signal_connect_object ((GObject*) _tmp2_, "notify::active", (GCallback) _adblock_config_active_changed_g_object_notify, self, 0);
#line 129 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp3_ = sub;
#line 129 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 129 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->subscriptions = g_list_append (self->priv->subscriptions, _tmp4_);
#line 130 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp5_ = self->priv->_size;
#line 130 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_set_size (self, _tmp5_ + 1);
#line 131 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp6_ = self->priv->should_save;
#line 131 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	if (_tmp6_) {
#line 132 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		adblock_config_update_filters (self);
#line 1343 "config.c"
	}
#line 133 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	result = TRUE;
#line 133 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return result;
#line 1349 "config.c"
}


void adblock_config_remove (AdblockConfig* self, AdblockSubscription* sub) {
	AdblockSubscription* _tmp0_;
	gboolean _tmp1_ = FALSE;
	AdblockSubscription* _tmp2_;
	AdblockSubscription* _tmp3_;
	guint _tmp4_ = 0U;
	GQuark _tmp5_ = 0U;
	guint _tmp6_;
#line 136 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 136 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (sub != NULL);
#line 137 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = sub;
#line 137 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp1_ = adblock_config_contains (self, _tmp0_);
#line 137 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	if (!_tmp1_) {
#line 138 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		return;
#line 1373 "config.c"
	}
#line 140 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp2_ = sub;
#line 140 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->subscriptions = g_list_remove (self->priv->subscriptions, _tmp2_);
#line 141 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp3_ = sub;
#line 141 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_signal_parse_name ("notify::active", G_TYPE_OBJECT, &_tmp4_, &_tmp5_, TRUE);
#line 141 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_signal_handlers_disconnect_matched ((GObject*) _tmp3_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_DETAIL | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp4_, _tmp5_, NULL, (GCallback) _adblock_config_active_changed_g_object_notify, self);
#line 142 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_update_filters (self);
#line 143 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp6_ = self->priv->_size;
#line 143 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_set_size (self, _tmp6_ - 1);
#line 1391 "config.c"
}


const gchar* adblock_config_get_path (AdblockConfig* self) {
	const gchar* result;
	const gchar* _tmp0_;
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = self->priv->_path;
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	result = _tmp0_;
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return result;
#line 1406 "config.c"
}


static void adblock_config_set_path (AdblockConfig* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = value;
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_g_free0 (self->priv->_path);
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->_path = _tmp1_;
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_object_notify ((GObject *) self, "path");
#line 1425 "config.c"
}


gboolean adblock_config_get_enabled (AdblockConfig* self) {
	gboolean result;
	gboolean _tmp0_;
#line 18 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 18 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = self->priv->_enabled;
#line 18 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	result = _tmp0_;
#line 18 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return result;
#line 1440 "config.c"
}


void adblock_config_set_enabled (AdblockConfig* self, gboolean value) {
	gboolean _tmp0_;
#line 18 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 18 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = value;
#line 18 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->_enabled = _tmp0_;
#line 18 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_object_notify ((GObject *) self, "enabled");
#line 1454 "config.c"
}


guint adblock_config_get_size (AdblockConfig* self) {
	guint result;
	guint _tmp0_;
#line 115 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_val_if_fail (self != NULL, 0U);
#line 115 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = self->priv->_size;
#line 115 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	result = _tmp0_;
#line 115 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	return result;
#line 1469 "config.c"
}


static void adblock_config_set_size (AdblockConfig* self, guint value) {
	guint _tmp0_;
#line 115 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_return_if_fail (self != NULL);
#line 115 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_tmp0_ = value;
#line 115 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv->_size = _tmp0_;
#line 115 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_object_notify ((GObject *) self, "size");
#line 1483 "config.c"
}


static void adblock_config_class_init (AdblockConfigClass * klass) {
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	adblock_config_parent_class = g_type_class_peek_parent (klass);
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_type_class_add_private (klass, sizeof (AdblockConfigPrivate));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_adblock_config_get_property;
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_adblock_config_set_property;
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	G_OBJECT_CLASS (klass)->finalize = adblock_config_finalize;
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ADBLOCK_CONFIG_PATH, g_param_spec_string ("path", "path", "path", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ADBLOCK_CONFIG_ENABLED, g_param_spec_boolean ("enabled", "enabled", "enabled", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ADBLOCK_CONFIG_SIZE, g_param_spec_uint ("size", "size", "size", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 1504 "config.c"
}


static void adblock_config_instance_init (AdblockConfig * self) {
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self->priv = ADBLOCK_CONFIG_GET_PRIVATE (self);
#line 1511 "config.c"
}


static void adblock_config_finalize (GObject* obj) {
	AdblockConfig * self;
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ADBLOCK_TYPE_CONFIG, AdblockConfig);
#line 14 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	__g_list_free__g_object_unref0_0 (self->priv->subscriptions);
#line 15 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_g_free0 (self->priv->_path);
#line 16 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	_g_key_file_free0 (self->priv->keyfile);
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	G_OBJECT_CLASS (adblock_config_parent_class)->finalize (obj);
#line 1527 "config.c"
}


GType adblock_config_get_type (void) {
	static volatile gsize adblock_config_type_id__volatile = 0;
	if (g_once_init_enter (&adblock_config_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AdblockConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) adblock_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AdblockConfig), 0, (GInstanceInitFunc) adblock_config_instance_init, NULL };
		GType adblock_config_type_id;
		adblock_config_type_id = g_type_register_static (G_TYPE_OBJECT, "AdblockConfig", &g_define_type_info, 0);
		g_once_init_leave (&adblock_config_type_id__volatile, adblock_config_type_id);
	}
	return adblock_config_type_id__volatile;
}


static void _vala_adblock_config_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	AdblockConfig * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ADBLOCK_TYPE_CONFIG, AdblockConfig);
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	switch (property_id) {
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		case ADBLOCK_CONFIG_PATH:
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_value_set_string (value, adblock_config_get_path (self));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		break;
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		case ADBLOCK_CONFIG_ENABLED:
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_value_set_boolean (value, adblock_config_get_enabled (self));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		break;
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		case ADBLOCK_CONFIG_SIZE:
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		g_value_set_uint (value, adblock_config_get_size (self));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		break;
#line 1566 "config.c"
		default:
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		break;
#line 1572 "config.c"
	}
}


static void _vala_adblock_config_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	AdblockConfig * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ADBLOCK_TYPE_CONFIG, AdblockConfig);
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
	switch (property_id) {
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		case ADBLOCK_CONFIG_PATH:
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		adblock_config_set_path (self, g_value_get_string (value));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		break;
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		case ADBLOCK_CONFIG_ENABLED:
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		adblock_config_set_enabled (self, g_value_get_boolean (value));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		break;
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		case ADBLOCK_CONFIG_SIZE:
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		adblock_config_set_size (self, g_value_get_uint (value));
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		break;
#line 1600 "config.c"
		default:
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/luyue/new/Webkit2Browser/Source/midori/extensions/adblock/config.vala"
		break;
#line 1606 "config.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



