/* updater.c generated by valac 0.20.1, the Vala compiler
 * generated from updater.vala, do not modify */

/*
 Copyright (C) 2014 Paweł Forysiuk <tuxator@o2.pl>
 Copyright (C) 2014 Christian Dywan <christian@twotoasts.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define ADBLOCK_TYPE_FEATURE (adblock_feature_get_type ())
#define ADBLOCK_FEATURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_FEATURE, AdblockFeature))
#define ADBLOCK_FEATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_FEATURE, AdblockFeatureClass))
#define ADBLOCK_IS_FEATURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_FEATURE))
#define ADBLOCK_IS_FEATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_FEATURE))
#define ADBLOCK_FEATURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_FEATURE, AdblockFeatureClass))

typedef struct _AdblockFeature AdblockFeature;
typedef struct _AdblockFeatureClass AdblockFeatureClass;
typedef struct _AdblockFeaturePrivate AdblockFeaturePrivate;

#define ADBLOCK_TYPE_DIRECTIVE (adblock_directive_get_type ())

#define ADBLOCK_TYPE_UPDATER (adblock_updater_get_type ())
#define ADBLOCK_UPDATER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_UPDATER, AdblockUpdater))
#define ADBLOCK_UPDATER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_UPDATER, AdblockUpdaterClass))
#define ADBLOCK_IS_UPDATER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_UPDATER))
#define ADBLOCK_IS_UPDATER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_UPDATER))
#define ADBLOCK_UPDATER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_UPDATER, AdblockUpdaterClass))

typedef struct _AdblockUpdater AdblockUpdater;
typedef struct _AdblockUpdaterClass AdblockUpdaterClass;
typedef struct _AdblockUpdaterPrivate AdblockUpdaterPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

typedef enum  {
	ADBLOCK_DIRECTIVE_ALLOW,
	ADBLOCK_DIRECTIVE_BLOCK
} AdblockDirective;

struct _AdblockFeature {
	GObject parent_instance;
	AdblockFeaturePrivate * priv;
};

struct _AdblockFeatureClass {
	GObjectClass parent_class;
	gboolean (*header) (AdblockFeature* self, const gchar* key, const gchar* value);
	gboolean (*parsed) (AdblockFeature* self, GFile* file);
	AdblockDirective* (*match) (AdblockFeature* self, const gchar* request_uri, const gchar* page_uri, GError** error);
	void (*clear) (AdblockFeature* self);
};

struct _AdblockUpdater {
	AdblockFeature parent_instance;
	AdblockUpdaterPrivate * priv;
};

struct _AdblockUpdaterClass {
	AdblockFeatureClass parent_class;
};

struct _AdblockUpdaterPrivate {
	gchar* expires_meta;
	gchar* last_mod_meta;
	GDateTime* _last_updated;
	GDateTime* _expires;
	gboolean _needs_update;
};


static gpointer adblock_updater_parent_class = NULL;

GType adblock_feature_get_type (void) G_GNUC_CONST;
GType adblock_directive_get_type (void) G_GNUC_CONST;
GType adblock_updater_get_type (void) G_GNUC_CONST;
#define ADBLOCK_UPDATER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ADBLOCK_TYPE_UPDATER, AdblockUpdaterPrivate))
enum  {
	ADBLOCK_UPDATER_DUMMY_PROPERTY,
	ADBLOCK_UPDATER_LAST_UPDATED,
	ADBLOCK_UPDATER_EXPIRES,
	ADBLOCK_UPDATER_NEEDS_UPDATE
};
AdblockUpdater* adblock_updater_new (void);
AdblockUpdater* adblock_updater_construct (GType object_type);
AdblockFeature* adblock_feature_construct (GType object_type);
static void adblock_updater_real_clear (AdblockFeature* base);
void adblock_updater_set_last_updated (AdblockUpdater* self, GDateTime* value);
void adblock_updater_set_expires (AdblockUpdater* self, GDateTime* value);
void adblock_updater_set_needs_update (AdblockUpdater* self, gboolean value);
static gboolean adblock_updater_real_header (AdblockFeature* base, const gchar* key, const gchar* value);
static gboolean adblock_updater_real_parsed (AdblockFeature* base, GFile* file);
static void adblock_updater_process_dates (AdblockUpdater* self, GFile* file);
static gint adblock_updater_get_month_from_string (AdblockUpdater* self, const gchar* month);
GDateTime* adblock_updater_get_last_updated (AdblockUpdater* self);
GDateTime* adblock_updater_get_expires (AdblockUpdater* self);
gboolean adblock_updater_get_needs_update (AdblockUpdater* self);
static void adblock_updater_finalize (GObject* obj);
static void _vala_adblock_updater_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_adblock_updater_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


AdblockUpdater* adblock_updater_construct (GType object_type) {
	AdblockUpdater * self = NULL;
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self = (AdblockUpdater*) adblock_feature_construct (object_type);
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return self;
#line 126 "updater.c"
}


AdblockUpdater* adblock_updater_new (void) {
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return adblock_updater_construct (ADBLOCK_TYPE_UPDATER);
#line 133 "updater.c"
}


static void adblock_updater_real_clear (AdblockFeature* base) {
	AdblockUpdater * self;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self = (AdblockUpdater*) base;
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_free0 (self->priv->expires_meta);
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self->priv->expires_meta = NULL;
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_free0 (self->priv->last_mod_meta);
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self->priv->last_mod_meta = NULL;
#line 27 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	adblock_updater_set_last_updated (self, NULL);
#line 28 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	adblock_updater_set_expires (self, NULL);
#line 29 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	adblock_updater_set_needs_update (self, FALSE);
#line 155 "updater.c"
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* end;
	gchar* _tmp3_;
#line 1157 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp0_ = str;
#line 1157 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp1_ = maxlen;
#line 1157 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
#line 1157 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	end = _tmp2_;
#line 1158 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp3_ = end;
#line 1158 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp3_ == NULL) {
#line 178 "updater.c"
		glong _tmp4_;
#line 1159 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp4_ = maxlen;
#line 1159 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		result = _tmp4_;
#line 1159 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		return result;
#line 186 "updater.c"
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
#line 1161 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp5_ = end;
#line 1161 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp6_ = str;
#line 1161 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		result = (glong) (_tmp5_ - _tmp6_);
#line 1161 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		return result;
#line 198 "updater.c"
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	gboolean _tmp3_;
	glong _tmp9_;
	glong _tmp15_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
#line 1168 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp1_ = offset;
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp1_ >= ((glong) 0)) {
#line 223 "updater.c"
		glong _tmp2_;
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp2_ = len;
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp0_ = _tmp2_ >= ((glong) 0);
#line 229 "updater.c"
	} else {
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 233 "updater.c"
	}
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp3_ = _tmp0_;
#line 1170 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp3_) {
#line 239 "updater.c"
		glong _tmp4_;
		glong _tmp5_;
		glong _tmp6_ = 0L;
#line 1172 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp4_ = offset;
#line 1172 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp5_ = len;
#line 1172 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
#line 1172 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		string_length = _tmp6_;
#line 251 "updater.c"
	} else {
		gint _tmp7_;
		gint _tmp8_;
#line 1174 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp7_ = strlen (self);
#line 1174 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp8_ = _tmp7_;
#line 1174 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		string_length = (glong) _tmp8_;
#line 261 "updater.c"
	}
#line 1177 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp9_ = offset;
#line 1177 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp9_ < ((glong) 0)) {
#line 267 "updater.c"
		glong _tmp10_;
		glong _tmp11_;
		glong _tmp12_;
#line 1178 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp10_ = string_length;
#line 1178 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp11_ = offset;
#line 1178 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		offset = _tmp10_ + _tmp11_;
#line 1179 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp12_ = offset;
#line 1179 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
#line 281 "updater.c"
	} else {
		glong _tmp13_;
		glong _tmp14_;
#line 1181 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp13_ = offset;
#line 1181 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp14_ = string_length;
#line 1181 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
#line 291 "updater.c"
	}
#line 1183 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp15_ = len;
#line 1183 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_tmp15_ < ((glong) 0)) {
#line 297 "updater.c"
		glong _tmp16_;
		glong _tmp17_;
#line 1184 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp16_ = string_length;
#line 1184 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp17_ = offset;
#line 1184 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		len = _tmp16_ - _tmp17_;
#line 306 "updater.c"
	}
#line 1186 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp18_ = offset;
#line 1186 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp19_ = len;
#line 1186 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp20_ = string_length;
#line 1186 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp21_ = offset;
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp22_ = len;
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	result = _tmp23_;
#line 1187 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	return result;
#line 326 "updater.c"
}


static gboolean adblock_updater_real_header (AdblockFeature* base, const gchar* key, const gchar* value) {
	AdblockUpdater * self;
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp4_;
#line 32 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self = (AdblockUpdater*) base;
#line 32 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_val_if_fail (key != NULL, FALSE);
#line 32 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_val_if_fail (value != NULL, FALSE);
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp1_ = key;
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp2_ = g_str_has_prefix (_tmp1_, "Last mod");
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	if (_tmp2_) {
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp0_ = TRUE;
#line 351 "updater.c"
	} else {
		const gchar* _tmp3_;
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp3_ = key;
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp0_ = g_strcmp0 (_tmp3_, "Updated") == 0;
#line 358 "updater.c"
	}
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp4_ = _tmp0_;
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	if (_tmp4_) {
#line 364 "updater.c"
		const gchar* _tmp5_;
		gchar* _tmp6_;
#line 34 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp5_ = value;
#line 34 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp6_ = g_strdup (_tmp5_);
#line 34 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_g_free0 (self->priv->last_mod_meta);
#line 34 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		self->priv->last_mod_meta = _tmp6_;
#line 35 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		result = TRUE;
#line 35 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		return result;
#line 379 "updater.c"
	} else {
		const gchar* _tmp7_;
#line 36 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp7_ = key;
#line 36 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		if (g_strcmp0 (_tmp7_, "Expires") == 0) {
#line 386 "updater.c"
			const gchar* _tmp8_;
			gchar* _tmp9_;
#line 38 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp8_ = value;
#line 38 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp9_ = g_strdup (_tmp8_);
#line 38 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_g_free0 (self->priv->expires_meta);
#line 38 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			self->priv->expires_meta = _tmp9_;
#line 39 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			result = TRUE;
#line 39 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			return result;
#line 401 "updater.c"
		} else {
			const gchar* _tmp10_;
			gboolean _tmp11_ = FALSE;
#line 40 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp10_ = key;
#line 40 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp11_ = g_str_has_prefix (_tmp10_, "! This list expires after");
#line 40 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (_tmp11_) {
#line 411 "updater.c"
				const gchar* _tmp12_;
				gchar* _tmp13_ = NULL;
#line 42 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp12_ = key;
#line 42 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp13_ = string_substring (_tmp12_, (glong) 26, (glong) (-1));
#line 42 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_g_free0 (self->priv->expires_meta);
#line 42 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				self->priv->expires_meta = _tmp13_;
#line 43 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				result = TRUE;
#line 43 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				return result;
#line 426 "updater.c"
			}
		}
	}
#line 45 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	result = FALSE;
#line 45 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return result;
#line 434 "updater.c"
}


static gboolean adblock_updater_real_parsed (AdblockFeature* base, GFile* file) {
	AdblockUpdater * self;
	gboolean result = FALSE;
	GFile* _tmp0_;
#line 48 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self = (AdblockUpdater*) base;
#line 48 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_val_if_fail (file != NULL, FALSE);
#line 49 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = file;
#line 49 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	adblock_updater_process_dates (self, _tmp0_);
#line 51 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	result = TRUE;
#line 51 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return result;
#line 454 "updater.c"
}


static gint adblock_updater_get_month_from_string (AdblockUpdater* self, const gchar* month) {
	gint result = 0;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar** _tmp13_ = NULL;
	gchar** months;
	gint months_length1;
	gint _months_size_;
#line 54 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 55 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = month;
#line 55 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	if (_tmp0_ == NULL) {
#line 56 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		result = 0;
#line 56 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		return result;
#line 487 "updater.c"
	}
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp1_ = g_strdup ("Jan");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp2_ = g_strdup ("Feb");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp3_ = g_strdup ("Mar");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp4_ = g_strdup ("Apr");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp5_ = g_strdup ("May");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp6_ = g_strdup ("Jun");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp7_ = g_strdup ("Jul");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp8_ = g_strdup ("Aug");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp9_ = g_strdup ("Sep");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp10_ = g_strdup ("Oct");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp11_ = g_strdup ("Nov");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp12_ = g_strdup ("Dec");
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_ = g_new0 (gchar*, 12 + 1);
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[0] = _tmp1_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[1] = _tmp2_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[2] = _tmp3_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[3] = _tmp4_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[4] = _tmp5_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[5] = _tmp6_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[6] = _tmp7_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[7] = _tmp8_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[8] = _tmp9_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[9] = _tmp10_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[10] = _tmp11_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp13_[11] = _tmp12_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	months = _tmp13_;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	months_length1 = 12;
#line 58 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_months_size_ = months_length1;
#line 545 "updater.c"
	{
		gint i;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		i = 0;
#line 550 "updater.c"
		{
			gboolean _tmp14_;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp14_ = TRUE;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			while (TRUE) {
#line 557 "updater.c"
				gboolean _tmp15_;
				gint _tmp17_;
				gchar** _tmp18_;
				gint _tmp18__length1;
				const gchar* _tmp19_;
				gchar** _tmp20_;
				gint _tmp20__length1;
				gint _tmp21_;
				const gchar* _tmp22_;
				gboolean _tmp23_ = FALSE;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp15_ = _tmp14_;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				if (!_tmp15_) {
#line 572 "updater.c"
					gint _tmp16_;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					_tmp16_ = i;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					i = _tmp16_ + 1;
#line 578 "updater.c"
				}
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp14_ = FALSE;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp17_ = i;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp18_ = months;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp18__length1 = months_length1;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				if (!(_tmp17_ <= _tmp18__length1)) {
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					break;
#line 592 "updater.c"
				}
#line 61 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp19_ = month;
#line 61 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp20_ = months;
#line 61 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp20__length1 = months_length1;
#line 61 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp21_ = i;
#line 61 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp22_ = _tmp20_[_tmp21_];
#line 61 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp23_ = g_str_has_prefix (_tmp19_, _tmp22_);
#line 61 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				if (_tmp23_) {
#line 608 "updater.c"
					gint _tmp24_;
#line 62 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					_tmp24_ = i;
#line 62 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					result = _tmp24_ + 1;
#line 62 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					months = (_vala_array_free (months, months_length1, (GDestroyNotify) g_free), NULL);
#line 62 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					return result;
#line 618 "updater.c"
				}
			}
		}
	}
#line 64 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	result = 0;
#line 64 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	months = (_vala_array_free (months, months_length1, (GDestroyNotify) g_free), NULL);
#line 64 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return result;
#line 629 "updater.c"
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_;
	gchar* _tmp1_ = NULL;
#line 1238 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1238 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1239 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp0_ = needle;
#line 1239 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
#line 1239 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	result = _tmp1_ != NULL;
#line 1239 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	return result;
#line 649 "updater.c"
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_;
	gchar _tmp1_;
#line 965 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 966 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp0_ = index;
#line 966 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	_tmp1_ = ((gchar*) self)[_tmp0_];
#line 966 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	result = _tmp1_;
#line 966 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	return result;
#line 667 "updater.c"
}


static void adblock_updater_process_dates (AdblockUpdater* self, GFile* file) {
	GDateTime* _tmp0_;
	GDateTime* now;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_;
	gboolean _tmp10_;
	const gchar* _tmp117_;
	GDateTime* _tmp144_;
	GDateTime* _tmp145_;
	gint _tmp146_ = 0;
#line 67 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_if_fail (self != NULL);
#line 67 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_if_fail (file != NULL);
#line 68 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 68 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	now = _tmp0_;
#line 69 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	adblock_updater_set_last_updated (self, NULL);
#line 70 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	adblock_updater_set_expires (self, NULL);
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp2_ = self->priv->last_mod_meta;
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	if (_tmp2_ != NULL) {
#line 697 "updater.c"
		gboolean _tmp3_ = FALSE;
		const gchar* _tmp4_;
		gboolean _tmp5_ = FALSE;
		gboolean _tmp9_;
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp4_ = self->priv->last_mod_meta;
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp5_ = string_contains (_tmp4_, " ");
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		if (_tmp5_) {
#line 708 "updater.c"
			const gchar* _tmp6_;
			gchar _tmp7_ = '\0';
			gboolean _tmp8_ = FALSE;
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp6_ = self->priv->last_mod_meta;
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp7_ = string_get (_tmp6_, (glong) 0);
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp8_ = g_ascii_isdigit (_tmp7_);
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp3_ = _tmp8_ == TRUE;
#line 720 "updater.c"
		} else {
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp3_ = FALSE;
#line 724 "updater.c"
		}
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp9_ = _tmp3_;
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp1_ = _tmp9_;
#line 730 "updater.c"
	} else {
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp1_ = FALSE;
#line 734 "updater.c"
	}
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp10_ = _tmp1_;
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	if (_tmp10_) {
#line 740 "updater.c"
		gint h;
		gint min;
		gint d = 0;
		gint m = 0;
		gint y = 0;
		gboolean _tmp11_ = FALSE;
		const gchar* _tmp12_;
		gboolean _tmp13_ = FALSE;
		gboolean _tmp16_;
		gint _tmp109_;
		gint _tmp110_;
		gint _tmp111_;
		gint _tmp112_;
		gint _tmp113_;
		GDateTime* _tmp114_;
		GDateTime* _tmp115_;
#line 74 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		h = 0;
#line 74 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		min = 0;
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp12_ = self->priv->last_mod_meta;
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp13_ = string_contains (_tmp12_, ".");
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		if (_tmp13_) {
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp11_ = TRUE;
#line 769 "updater.c"
		} else {
			const gchar* _tmp14_;
			gboolean _tmp15_ = FALSE;
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp14_ = self->priv->last_mod_meta;
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp15_ = string_contains (_tmp14_, "-");
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp11_ = _tmp15_;
#line 779 "updater.c"
		}
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp16_ = _tmp11_;
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		if (_tmp16_) {
#line 785 "updater.c"
			const gchar* _tmp17_;
			gchar** _tmp18_;
			gchar** _tmp19_ = NULL;
			gchar** parts;
			gint parts_length1;
			gint _parts_size_;
			gchar** date_parts = NULL;
			gint date_parts_length1 = 0;
			gint _date_parts_size_ = 0;
			gchar* _tmp20_;
			gchar* split_char;
			gboolean _tmp21_ = FALSE;
			gchar** _tmp22_;
			gint _tmp22__length1;
			const gchar* _tmp23_;
			gboolean _tmp27_;
			gchar** _tmp38_;
			gint _tmp38__length1;
			const gchar* _tmp39_;
			gboolean _tmp40_ = FALSE;
			gchar** _tmp46_;
			gint _tmp46__length1;
			const gchar* _tmp47_;
			const gchar* _tmp48_;
			gchar** _tmp49_;
			gchar** _tmp50_ = NULL;
			gchar** _tmp51_;
			gint _tmp51__length1;
			const gchar* _tmp52_;
			gint _tmp53_ = 0;
			gchar** _tmp54_;
			gint _tmp54__length1;
			const gchar* _tmp55_;
			gint _tmp56_;
			gint _tmp57_;
#line 77 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp17_ = self->priv->last_mod_meta;
#line 77 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp19_ = _tmp18_ = g_strsplit (_tmp17_, " ", 2);
#line 77 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts = _tmp19_;
#line 77 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts_length1 = _vala_array_length (_tmp18_);
#line 77 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_parts_size_ = parts_length1;
#line 79 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp20_ = g_strdup (" ");
#line 79 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			split_char = _tmp20_;
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp22_ = parts;
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp22__length1 = parts_length1;
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp23_ = _tmp22_[1];
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (g_strcmp0 (_tmp23_, "") != 0) {
#line 843 "updater.c"
				gchar** _tmp24_;
				gint _tmp24__length1;
				const gchar* _tmp25_;
				gboolean _tmp26_ = FALSE;
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp24_ = parts;
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp24__length1 = parts_length1;
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp25_ = _tmp24_[1];
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp26_ = string_contains (_tmp25_, ":");
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp21_ = _tmp26_;
#line 858 "updater.c"
			} else {
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp21_ = FALSE;
#line 862 "updater.c"
			}
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp27_ = _tmp21_;
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (_tmp27_) {
#line 868 "updater.c"
				gchar** _tmp28_;
				gint _tmp28__length1;
				const gchar* _tmp29_;
				gchar** _tmp30_;
				gchar** _tmp31_ = NULL;
				gchar** time_parts;
				gint time_parts_length1;
				gint _time_parts_size_;
				gchar** _tmp32_;
				gint _tmp32__length1;
				const gchar* _tmp33_;
				gint _tmp34_ = 0;
				gchar** _tmp35_;
				gint _tmp35__length1;
				const gchar* _tmp36_;
				gint _tmp37_ = 0;
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp28_ = parts;
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp28__length1 = parts_length1;
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp29_ = _tmp28_[1];
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp31_ = _tmp30_ = g_strsplit (_tmp29_, ":", 2);
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				time_parts = _tmp31_;
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				time_parts_length1 = _vala_array_length (_tmp30_);
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_time_parts_size_ = time_parts_length1;
#line 84 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp32_ = time_parts;
#line 84 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp32__length1 = time_parts_length1;
#line 84 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp33_ = _tmp32_[0];
#line 84 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp34_ = atoi (_tmp33_);
#line 84 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				h = _tmp34_;
#line 85 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp35_ = time_parts;
#line 85 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp35__length1 = time_parts_length1;
#line 85 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp36_ = _tmp35_[1];
#line 85 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp37_ = atoi (_tmp36_);
#line 85 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				min = _tmp37_;
#line 82 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				time_parts = (_vala_array_free (time_parts, time_parts_length1, (GDestroyNotify) g_free), NULL);
#line 921 "updater.c"
			}
#line 89 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp38_ = parts;
#line 89 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp38__length1 = parts_length1;
#line 89 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp39_ = _tmp38_[0];
#line 89 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp40_ = string_contains (_tmp39_, ".");
#line 89 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (_tmp40_) {
#line 933 "updater.c"
				gchar* _tmp41_;
#line 90 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp41_ = g_strdup (".");
#line 90 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_g_free0 (split_char);
#line 90 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				split_char = _tmp41_;
#line 941 "updater.c"
			} else {
				gchar** _tmp42_;
				gint _tmp42__length1;
				const gchar* _tmp43_;
				gboolean _tmp44_ = FALSE;
#line 91 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp42_ = parts;
#line 91 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp42__length1 = parts_length1;
#line 91 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp43_ = _tmp42_[0];
#line 91 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp44_ = string_contains (_tmp43_, "-");
#line 91 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				if (_tmp44_) {
#line 957 "updater.c"
					gchar* _tmp45_;
#line 92 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					_tmp45_ = g_strdup ("-");
#line 92 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					_g_free0 (split_char);
#line 92 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
					split_char = _tmp45_;
#line 965 "updater.c"
				}
			}
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp46_ = parts;
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp46__length1 = parts_length1;
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp47_ = _tmp46_[0];
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp48_ = split_char;
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp50_ = _tmp49_ = g_strsplit (_tmp47_, _tmp48_, 3);
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			date_parts = (_vala_array_free (date_parts, date_parts_length1, (GDestroyNotify) g_free), NULL);
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			date_parts = _tmp50_;
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			date_parts_length1 = _vala_array_length (_tmp49_);
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_date_parts_size_ = date_parts_length1;
#line 95 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp51_ = date_parts;
#line 95 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp51__length1 = date_parts_length1;
#line 95 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp52_ = _tmp51_[1];
#line 95 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp53_ = atoi (_tmp52_);
#line 95 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			m = _tmp53_;
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp54_ = date_parts;
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp54__length1 = date_parts_length1;
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp55_ = _tmp54_[2];
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp56_ = strlen (_tmp55_);
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp57_ = _tmp56_;
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (_tmp57_ == 4) {
#line 1008 "updater.c"
				gchar** _tmp58_;
				gint _tmp58__length1;
				const gchar* _tmp59_;
				gint _tmp60_ = 0;
				gchar** _tmp61_;
				gint _tmp61__length1;
				const gchar* _tmp62_;
				gint _tmp63_ = 0;
#line 97 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp58_ = date_parts;
#line 97 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp58__length1 = date_parts_length1;
#line 97 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp59_ = _tmp58_[2];
#line 97 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp60_ = atoi (_tmp59_);
#line 97 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				y = _tmp60_;
#line 98 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp61_ = date_parts;
#line 98 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp61__length1 = date_parts_length1;
#line 98 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp62_ = _tmp61_[0];
#line 98 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp63_ = atoi (_tmp62_);
#line 98 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				d = _tmp63_;
#line 1037 "updater.c"
			} else {
				gchar** _tmp64_;
				gint _tmp64__length1;
				const gchar* _tmp65_;
				gint _tmp66_ = 0;
				gchar** _tmp67_;
				gint _tmp67__length1;
				const gchar* _tmp68_;
				gint _tmp69_ = 0;
#line 100 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp64_ = date_parts;
#line 100 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp64__length1 = date_parts_length1;
#line 100 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp65_ = _tmp64_[0];
#line 100 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp66_ = atoi (_tmp65_);
#line 100 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				y = _tmp66_;
#line 101 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp67_ = date_parts;
#line 101 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp67__length1 = date_parts_length1;
#line 101 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp68_ = _tmp67_[2];
#line 101 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp69_ = atoi (_tmp68_);
#line 101 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				d = _tmp69_;
#line 1067 "updater.c"
			}
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_g_free0 (split_char);
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			date_parts = (_vala_array_free (date_parts, date_parts_length1, (GDestroyNotify) g_free), NULL);
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 1075 "updater.c"
		} else {
			const gchar* _tmp70_;
			gchar** _tmp71_;
			gchar** _tmp72_ = NULL;
			gchar** parts;
			gint parts_length1;
			gint _parts_size_;
			gboolean _tmp73_ = FALSE;
			gchar** _tmp74_;
			gint _tmp74__length1;
			const gchar* _tmp75_;
			gboolean _tmp79_;
			gchar** _tmp90_;
			gint _tmp90__length1;
			const gchar* _tmp91_;
			gint _tmp92_ = 0;
			gchar** _tmp93_;
			gint _tmp93__length1;
			const gchar* _tmp94_;
			gint _tmp95_;
			gint _tmp96_;
#line 104 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp70_ = self->priv->last_mod_meta;
#line 104 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp72_ = _tmp71_ = g_strsplit (_tmp70_, " ", 4);
#line 104 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts = _tmp72_;
#line 104 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts_length1 = _vala_array_length (_tmp71_);
#line 104 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_parts_size_ = parts_length1;
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp74_ = parts;
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp74__length1 = parts_length1;
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp75_ = _tmp74_[3];
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (_tmp75_ != NULL) {
#line 1115 "updater.c"
				gchar** _tmp76_;
				gint _tmp76__length1;
				const gchar* _tmp77_;
				gboolean _tmp78_ = FALSE;
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp76_ = parts;
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp76__length1 = parts_length1;
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp77_ = _tmp76_[3];
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp78_ = string_contains (_tmp77_, ":");
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp73_ = _tmp78_;
#line 1130 "updater.c"
			} else {
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp73_ = FALSE;
#line 1134 "updater.c"
			}
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp79_ = _tmp73_;
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (_tmp79_) {
#line 1140 "updater.c"
				gchar** _tmp80_;
				gint _tmp80__length1;
				const gchar* _tmp81_;
				gchar** _tmp82_;
				gchar** _tmp83_ = NULL;
				gchar** time_parts;
				gint time_parts_length1;
				gint _time_parts_size_;
				gchar** _tmp84_;
				gint _tmp84__length1;
				const gchar* _tmp85_;
				gint _tmp86_ = 0;
				gchar** _tmp87_;
				gint _tmp87__length1;
				const gchar* _tmp88_;
				gint _tmp89_ = 0;
#line 107 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp80_ = parts;
#line 107 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp80__length1 = parts_length1;
#line 107 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp81_ = _tmp80_[3];
#line 107 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp83_ = _tmp82_ = g_strsplit (_tmp81_, ":", 2);
#line 107 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				time_parts = _tmp83_;
#line 107 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				time_parts_length1 = _vala_array_length (_tmp82_);
#line 107 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_time_parts_size_ = time_parts_length1;
#line 108 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp84_ = time_parts;
#line 108 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp84__length1 = time_parts_length1;
#line 108 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp85_ = _tmp84_[0];
#line 108 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp86_ = atoi (_tmp85_);
#line 108 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				h = _tmp86_;
#line 109 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp87_ = time_parts;
#line 109 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp87__length1 = time_parts_length1;
#line 109 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp88_ = _tmp87_[1];
#line 109 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp89_ = atoi (_tmp88_);
#line 109 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				min = _tmp89_;
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				time_parts = (_vala_array_free (time_parts, time_parts_length1, (GDestroyNotify) g_free), NULL);
#line 1193 "updater.c"
			}
#line 112 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp90_ = parts;
#line 112 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp90__length1 = parts_length1;
#line 112 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp91_ = _tmp90_[1];
#line 112 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp92_ = adblock_updater_get_month_from_string (self, _tmp91_);
#line 112 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			m = _tmp92_;
#line 113 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp93_ = parts;
#line 113 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp93__length1 = parts_length1;
#line 113 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp94_ = _tmp93_[2];
#line 113 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp95_ = strlen (_tmp94_);
#line 113 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp96_ = _tmp95_;
#line 113 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (_tmp96_ == 4) {
#line 1217 "updater.c"
				gchar** _tmp97_;
				gint _tmp97__length1;
				const gchar* _tmp98_;
				gint _tmp99_ = 0;
				gchar** _tmp100_;
				gint _tmp100__length1;
				const gchar* _tmp101_;
				gint _tmp102_ = 0;
#line 114 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp97_ = parts;
#line 114 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp97__length1 = parts_length1;
#line 114 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp98_ = _tmp97_[2];
#line 114 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp99_ = atoi (_tmp98_);
#line 114 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				y = _tmp99_;
#line 115 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp100_ = parts;
#line 115 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp100__length1 = parts_length1;
#line 115 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp101_ = _tmp100_[0];
#line 115 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp102_ = atoi (_tmp101_);
#line 115 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				d = _tmp102_;
#line 1246 "updater.c"
			} else {
				gchar** _tmp103_;
				gint _tmp103__length1;
				const gchar* _tmp104_;
				gint _tmp105_ = 0;
				gchar** _tmp106_;
				gint _tmp106__length1;
				const gchar* _tmp107_;
				gint _tmp108_ = 0;
#line 117 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp103_ = parts;
#line 117 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp103__length1 = parts_length1;
#line 117 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp104_ = _tmp103_[0];
#line 117 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp105_ = atoi (_tmp104_);
#line 117 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				y = _tmp105_;
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp106_ = parts;
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp106__length1 = parts_length1;
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp107_ = _tmp106_[2];
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp108_ = atoi (_tmp107_);
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				d = _tmp108_;
#line 1276 "updater.c"
			}
#line 76 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 1280 "updater.c"
		}
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp109_ = y;
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp110_ = m;
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp111_ = d;
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp112_ = h;
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp113_ = min;
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp114_ = g_date_time_new_local (_tmp109_, _tmp110_, _tmp111_, _tmp112_, _tmp113_, 0.0);
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp115_ = _tmp114_;
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		adblock_updater_set_last_updated (self, _tmp115_);
#line 122 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_g_date_time_unref0 (_tmp115_);
#line 1300 "updater.c"
	} else {
		GDateTime* _tmp116_;
#line 133 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp116_ = now;
#line 133 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		adblock_updater_set_last_updated (self, _tmp116_);
#line 1307 "updater.c"
	}
#line 137 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp117_ = self->priv->expires_meta;
#line 137 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	if (_tmp117_ != NULL) {
#line 1313 "updater.c"
		const gchar* _tmp118_;
		gboolean _tmp119_ = FALSE;
#line 138 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp118_ = self->priv->expires_meta;
#line 138 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp119_ = string_contains (_tmp118_, "days");
#line 138 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		if (_tmp119_) {
#line 1322 "updater.c"
			const gchar* _tmp120_;
			gchar** _tmp121_;
			gchar** _tmp122_ = NULL;
			gchar** parts;
			gint parts_length1;
			gint _parts_size_;
			GDateTime* _tmp123_;
			gchar** _tmp124_;
			gint _tmp124__length1;
			const gchar* _tmp125_;
			gint _tmp126_ = 0;
			GDateTime* _tmp127_ = NULL;
			GDateTime* _tmp128_;
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp120_ = self->priv->expires_meta;
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp122_ = _tmp121_ = g_strsplit (_tmp120_, " ", 0);
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts = _tmp122_;
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts_length1 = _vala_array_length (_tmp121_);
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_parts_size_ = parts_length1;
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp123_ = self->priv->_last_updated;
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp124_ = parts;
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp124__length1 = parts_length1;
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp125_ = _tmp124_[0];
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp126_ = atoi (_tmp125_);
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp127_ = g_date_time_add_days (_tmp123_, _tmp126_);
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp128_ = _tmp127_;
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			adblock_updater_set_expires (self, _tmp128_);
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_g_date_time_unref0 (_tmp128_);
#line 138 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 1366 "updater.c"
		} else {
			const gchar* _tmp129_;
			gboolean _tmp130_ = FALSE;
#line 141 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp129_ = self->priv->expires_meta;
#line 141 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			_tmp130_ = string_contains (_tmp129_, "hours");
#line 141 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
			if (_tmp130_) {
#line 1376 "updater.c"
				const gchar* _tmp131_;
				gchar** _tmp132_;
				gchar** _tmp133_ = NULL;
				gchar** parts;
				gint parts_length1;
				gint _parts_size_;
				GDateTime* _tmp134_;
				gchar** _tmp135_;
				gint _tmp135__length1;
				const gchar* _tmp136_;
				gint _tmp137_ = 0;
				GDateTime* _tmp138_ = NULL;
				GDateTime* _tmp139_;
#line 142 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp131_ = self->priv->expires_meta;
#line 142 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp133_ = _tmp132_ = g_strsplit (_tmp131_, " ", 0);
#line 142 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				parts = _tmp133_;
#line 142 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				parts_length1 = _vala_array_length (_tmp132_);
#line 142 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_parts_size_ = parts_length1;
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp134_ = self->priv->_last_updated;
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp135_ = parts;
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp135__length1 = parts_length1;
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp136_ = _tmp135_[0];
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp137_ = atoi (_tmp136_);
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp138_ = g_date_time_add_hours (_tmp134_, _tmp137_);
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_tmp139_ = _tmp138_;
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				adblock_updater_set_expires (self, _tmp139_);
#line 143 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				_g_date_time_unref0 (_tmp139_);
#line 141 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
				parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 1420 "updater.c"
			}
		}
	} else {
		gint days_to_expire;
		GDateTime* _tmp140_;
		gint _tmp141_;
		GDateTime* _tmp142_ = NULL;
		GDateTime* _tmp143_;
#line 147 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		days_to_expire = 7;
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp140_ = self->priv->_last_updated;
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp141_ = days_to_expire;
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp142_ = g_date_time_add_days (_tmp140_, _tmp141_);
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_tmp143_ = _tmp142_;
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		adblock_updater_set_expires (self, _tmp143_);
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		_g_date_time_unref0 (_tmp143_);
#line 1443 "updater.c"
	}
#line 152 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp144_ = now;
#line 152 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp145_ = self->priv->_expires;
#line 152 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp146_ = g_date_time_compare (_tmp144_, _tmp145_);
#line 152 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	adblock_updater_set_needs_update (self, _tmp146_ == 1);
#line 67 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_date_time_unref0 (now);
#line 1455 "updater.c"
}


GDateTime* adblock_updater_get_last_updated (AdblockUpdater* self) {
	GDateTime* result;
	GDateTime* _tmp0_;
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = self->priv->_last_updated;
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	result = _tmp0_;
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return result;
#line 1470 "updater.c"
}


static gpointer _g_date_time_ref0 (gpointer self) {
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return self ? g_date_time_ref (self) : NULL;
#line 1477 "updater.c"
}


void adblock_updater_set_last_updated (AdblockUpdater* self, GDateTime* value) {
	GDateTime* _tmp0_;
	GDateTime* _tmp1_;
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_if_fail (self != NULL);
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = value;
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp1_ = _g_date_time_ref0 (_tmp0_);
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_date_time_unref0 (self->priv->_last_updated);
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self->priv->_last_updated = _tmp1_;
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_object_notify ((GObject *) self, "last-updated");
#line 1496 "updater.c"
}


GDateTime* adblock_updater_get_expires (AdblockUpdater* self) {
	GDateTime* result;
	GDateTime* _tmp0_;
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = self->priv->_expires;
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	result = _tmp0_;
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return result;
#line 1511 "updater.c"
}


void adblock_updater_set_expires (AdblockUpdater* self, GDateTime* value) {
	GDateTime* _tmp0_;
	GDateTime* _tmp1_;
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_if_fail (self != NULL);
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = value;
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp1_ = _g_date_time_ref0 (_tmp0_);
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_date_time_unref0 (self->priv->_expires);
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self->priv->_expires = _tmp1_;
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_object_notify ((GObject *) self, "expires");
#line 1530 "updater.c"
}


gboolean adblock_updater_get_needs_update (AdblockUpdater* self) {
	gboolean result;
	gboolean _tmp0_;
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = self->priv->_needs_update;
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	result = _tmp0_;
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	return result;
#line 1545 "updater.c"
}


void adblock_updater_set_needs_update (AdblockUpdater* self, gboolean value) {
	gboolean _tmp0_;
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_return_if_fail (self != NULL);
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_tmp0_ = value;
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self->priv->_needs_update = _tmp0_;
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_object_notify ((GObject *) self, "needs-update");
#line 1559 "updater.c"
}


static void adblock_updater_class_init (AdblockUpdaterClass * klass) {
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	adblock_updater_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_type_class_add_private (klass, sizeof (AdblockUpdaterPrivate));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	ADBLOCK_FEATURE_CLASS (klass)->clear = adblock_updater_real_clear;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	ADBLOCK_FEATURE_CLASS (klass)->header = adblock_updater_real_header;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	ADBLOCK_FEATURE_CLASS (klass)->parsed = adblock_updater_real_parsed;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_adblock_updater_get_property;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_adblock_updater_set_property;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	G_OBJECT_CLASS (klass)->finalize = adblock_updater_finalize;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ADBLOCK_UPDATER_LAST_UPDATED, g_param_spec_boxed ("last-updated", "last-updated", "last-updated", G_TYPE_DATE_TIME, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ADBLOCK_UPDATER_EXPIRES, g_param_spec_boxed ("expires", "expires", "expires", G_TYPE_DATE_TIME, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ADBLOCK_UPDATER_NEEDS_UPDATE, g_param_spec_boolean ("needs-update", "needs-update", "needs-update", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 1586 "updater.c"
}


static void adblock_updater_instance_init (AdblockUpdater * self) {
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self->priv = ADBLOCK_UPDATER_GET_PRIVATE (self);
#line 1593 "updater.c"
}


static void adblock_updater_finalize (GObject* obj) {
	AdblockUpdater * self;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ADBLOCK_TYPE_UPDATER, AdblockUpdater);
#line 15 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_free0 (self->priv->expires_meta);
#line 16 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_free0 (self->priv->last_mod_meta);
#line 17 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_date_time_unref0 (self->priv->_last_updated);
#line 18 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	_g_date_time_unref0 (self->priv->_expires);
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	G_OBJECT_CLASS (adblock_updater_parent_class)->finalize (obj);
#line 1611 "updater.c"
}


GType adblock_updater_get_type (void) {
	static volatile gsize adblock_updater_type_id__volatile = 0;
	if (g_once_init_enter (&adblock_updater_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AdblockUpdaterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) adblock_updater_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AdblockUpdater), 0, (GInstanceInitFunc) adblock_updater_instance_init, NULL };
		GType adblock_updater_type_id;
		adblock_updater_type_id = g_type_register_static (ADBLOCK_TYPE_FEATURE, "AdblockUpdater", &g_define_type_info, 0);
		g_once_init_leave (&adblock_updater_type_id__volatile, adblock_updater_type_id);
	}
	return adblock_updater_type_id__volatile;
}


static void _vala_adblock_updater_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	AdblockUpdater * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ADBLOCK_TYPE_UPDATER, AdblockUpdater);
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	switch (property_id) {
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		case ADBLOCK_UPDATER_LAST_UPDATED:
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		g_value_set_boxed (value, adblock_updater_get_last_updated (self));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		break;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		case ADBLOCK_UPDATER_EXPIRES:
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		g_value_set_boxed (value, adblock_updater_get_expires (self));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		break;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		case ADBLOCK_UPDATER_NEEDS_UPDATE:
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		g_value_set_boolean (value, adblock_updater_get_needs_update (self));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		break;
#line 1650 "updater.c"
		default:
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		break;
#line 1656 "updater.c"
	}
}


static void _vala_adblock_updater_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	AdblockUpdater * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ADBLOCK_TYPE_UPDATER, AdblockUpdater);
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
	switch (property_id) {
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		case ADBLOCK_UPDATER_LAST_UPDATED:
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		adblock_updater_set_last_updated (self, g_value_get_boxed (value));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		break;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		case ADBLOCK_UPDATER_EXPIRES:
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		adblock_updater_set_expires (self, g_value_get_boxed (value));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		break;
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		case ADBLOCK_UPDATER_NEEDS_UPDATE:
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		adblock_updater_set_needs_update (self, g_value_get_boolean (value));
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		break;
#line 1684 "updater.c"
		default:
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/updater.vala"
		break;
#line 1690 "updater.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



