/* whitelist.c generated by valac 0.20.1, the Vala compiler
 * generated from whitelist.vala, do not modify */

/*
 Copyright (C) 2014 Christian Dywan <christian@twotoasts.de>
 Copyright (C) 2014 Paweł Forysiuk <tuxator@o2.pl>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define ADBLOCK_TYPE_FEATURE (adblock_feature_get_type ())
#define ADBLOCK_FEATURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_FEATURE, AdblockFeature))
#define ADBLOCK_FEATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_FEATURE, AdblockFeatureClass))
#define ADBLOCK_IS_FEATURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_FEATURE))
#define ADBLOCK_IS_FEATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_FEATURE))
#define ADBLOCK_FEATURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_FEATURE, AdblockFeatureClass))

typedef struct _AdblockFeature AdblockFeature;
typedef struct _AdblockFeatureClass AdblockFeatureClass;
typedef struct _AdblockFeaturePrivate AdblockFeaturePrivate;

#define ADBLOCK_TYPE_DIRECTIVE (adblock_directive_get_type ())

#define ADBLOCK_TYPE_FILTER (adblock_filter_get_type ())
#define ADBLOCK_FILTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_FILTER, AdblockFilter))
#define ADBLOCK_FILTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_FILTER, AdblockFilterClass))
#define ADBLOCK_IS_FILTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_FILTER))
#define ADBLOCK_IS_FILTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_FILTER))
#define ADBLOCK_FILTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_FILTER, AdblockFilterClass))

typedef struct _AdblockFilter AdblockFilter;
typedef struct _AdblockFilterClass AdblockFilterClass;
typedef struct _AdblockFilterPrivate AdblockFilterPrivate;

#define ADBLOCK_TYPE_WHITELIST (adblock_whitelist_get_type ())
#define ADBLOCK_WHITELIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_WHITELIST, AdblockWhitelist))
#define ADBLOCK_WHITELIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_WHITELIST, AdblockWhitelistClass))
#define ADBLOCK_IS_WHITELIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_WHITELIST))
#define ADBLOCK_IS_WHITELIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_WHITELIST))
#define ADBLOCK_WHITELIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_WHITELIST, AdblockWhitelistClass))

typedef struct _AdblockWhitelist AdblockWhitelist;
typedef struct _AdblockWhitelistClass AdblockWhitelistClass;
typedef struct _AdblockWhitelistPrivate AdblockWhitelistPrivate;

#define ADBLOCK_TYPE_OPTIONS (adblock_options_get_type ())
#define ADBLOCK_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ADBLOCK_TYPE_OPTIONS, AdblockOptions))
#define ADBLOCK_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ADBLOCK_TYPE_OPTIONS, AdblockOptionsClass))
#define ADBLOCK_IS_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ADBLOCK_TYPE_OPTIONS))
#define ADBLOCK_IS_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ADBLOCK_TYPE_OPTIONS))
#define ADBLOCK_OPTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ADBLOCK_TYPE_OPTIONS, AdblockOptionsClass))

typedef struct _AdblockOptions AdblockOptions;
typedef struct _AdblockOptionsClass AdblockOptionsClass;
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

typedef enum  {
	ADBLOCK_DIRECTIVE_ALLOW,
	ADBLOCK_DIRECTIVE_BLOCK
} AdblockDirective;

struct _AdblockFeature {
	GObject parent_instance;
	AdblockFeaturePrivate * priv;
};

struct _AdblockFeatureClass {
	GObjectClass parent_class;
	gboolean (*header) (AdblockFeature* self, const gchar* key, const gchar* value);
	gboolean (*parsed) (AdblockFeature* self, GFile* file);
	AdblockDirective* (*match) (AdblockFeature* self, const gchar* request_uri, const gchar* page_uri, GError** error);
	void (*clear) (AdblockFeature* self);
};

struct _AdblockFilter {
	AdblockFeature parent_instance;
	AdblockFilterPrivate * priv;
	GHashTable* rules;
};

struct _AdblockFilterClass {
	AdblockFeatureClass parent_class;
	void (*insert) (AdblockFilter* self, const gchar* sig, GRegex* regex);
	GRegex* (*lookup) (AdblockFilter* self, const gchar* sig);
	guint (*size) (AdblockFilter* self);
};

struct _AdblockWhitelist {
	AdblockFilter parent_instance;
	AdblockWhitelistPrivate * priv;
};

struct _AdblockWhitelistClass {
	AdblockFilterClass parent_class;
};


static gpointer adblock_whitelist_parent_class = NULL;

GType adblock_feature_get_type (void) G_GNUC_CONST;
GType adblock_directive_get_type (void) G_GNUC_CONST;
GType adblock_filter_get_type (void) G_GNUC_CONST;
GType adblock_whitelist_get_type (void) G_GNUC_CONST;
enum  {
	ADBLOCK_WHITELIST_DUMMY_PROPERTY
};
GType adblock_options_get_type (void) G_GNUC_CONST;
AdblockWhitelist* adblock_whitelist_new (AdblockOptions* options);
AdblockWhitelist* adblock_whitelist_construct (GType object_type, AdblockOptions* options);
AdblockFilter* adblock_filter_construct (GType object_type, AdblockOptions* options);
static AdblockDirective* adblock_whitelist_real_match (AdblockFeature* base, const gchar* request_uri, const gchar* page_uri, GError** error);
static AdblockDirective* _adblock_directive_dup (AdblockDirective* self);


AdblockWhitelist* adblock_whitelist_construct (GType object_type, AdblockOptions* options) {
	AdblockWhitelist * self = NULL;
	AdblockOptions* _tmp0_;
#line 15 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	g_return_val_if_fail (options != NULL, NULL);
#line 16 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	_tmp0_ = options;
#line 16 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	self = (AdblockWhitelist*) adblock_filter_construct (object_type, _tmp0_);
#line 15 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	return self;
#line 140 "whitelist.c"
}


AdblockWhitelist* adblock_whitelist_new (AdblockOptions* options) {
#line 15 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	return adblock_whitelist_construct (ADBLOCK_TYPE_WHITELIST, options);
#line 147 "whitelist.c"
}


static gpointer _g_regex_ref0 (gpointer self) {
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	return self ? g_regex_ref (self) : NULL;
#line 154 "whitelist.c"
}


static AdblockDirective* _adblock_directive_dup (AdblockDirective* self) {
	AdblockDirective* dup;
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	dup = g_new0 (AdblockDirective, 1);
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	memcpy (dup, self, sizeof (AdblockDirective));
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	return dup;
#line 166 "whitelist.c"
}


static gpointer __adblock_directive_dup0 (gpointer self) {
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	return self ? _adblock_directive_dup (self) : NULL;
#line 173 "whitelist.c"
}


static AdblockDirective* adblock_whitelist_real_match (AdblockFeature* base, const gchar* request_uri, const gchar* page_uri, GError** error) {
	AdblockWhitelist * self;
	AdblockDirective* result = NULL;
	GHashTable* _tmp0_;
	GList* _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	self = (AdblockWhitelist*) base;
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	g_return_val_if_fail (request_uri != NULL, NULL);
#line 19 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	g_return_val_if_fail (page_uri != NULL, NULL);
#line 20 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	_tmp0_ = ((AdblockFilter*) self)->rules;
#line 20 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	_tmp1_ = g_hash_table_get_keys (_tmp0_);
#line 193 "whitelist.c"
	{
		GList* white_collection = NULL;
		GList* white_it = NULL;
#line 20 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
		white_collection = _tmp1_;
#line 20 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
		for (white_it = white_collection; white_it != NULL; white_it = white_it->next) {
#line 201 "whitelist.c"
			const gchar* white = NULL;
#line 20 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
			white = (const gchar*) white_it->data;
#line 205 "whitelist.c"
			{
				GHashTable* _tmp2_;
				const gchar* _tmp3_;
				gconstpointer _tmp4_ = NULL;
				GRegex* _tmp5_;
				GRegex* regex;
				GRegex* _tmp6_;
				const gchar* _tmp7_;
				gboolean _tmp8_ = FALSE;
				gboolean _tmp9_;
				GRegex* _tmp10_;
				const gchar* _tmp11_ = NULL;
				const gchar* _tmp12_;
				gboolean _tmp13_ = FALSE;
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp2_ = ((AdblockFilter*) self)->rules;
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp3_ = white;
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp4_ = g_hash_table_lookup (_tmp2_, _tmp3_);
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp5_ = _g_regex_ref0 ((GRegex*) _tmp4_);
#line 21 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				regex = _tmp5_;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp6_ = regex;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp7_ = request_uri;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp8_ = g_regex_match_full (_tmp6_, _tmp7_, (gssize) (-1), 0, 0, NULL, &_inner_error_);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp9_ = _tmp8_;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				if (_inner_error_ != NULL) {
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					g_propagate_error (error, _inner_error_);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					_g_regex_unref0 (regex);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					_g_list_free0 (white_collection);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					return NULL;
#line 248 "whitelist.c"
				}
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				if (!_tmp9_) {
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					result = NULL;
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					_g_regex_unref0 (regex);
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					_g_list_free0 (white_collection);
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					return result;
#line 260 "whitelist.c"
				}
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp10_ = regex;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp11_ = g_regex_get_pattern (_tmp10_);
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp12_ = request_uri;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_tmp13_ = g_regex_match_simple (_tmp11_, _tmp12_, G_REGEX_UNGREEDY, G_REGEX_MATCH_NOTEMPTY);
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				if (_tmp13_) {
#line 272 "whitelist.c"
					AdblockDirective _tmp14_;
					AdblockDirective* _tmp15_;
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					_tmp14_ = ADBLOCK_DIRECTIVE_ALLOW;
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					_tmp15_ = __adblock_directive_dup0 (&_tmp14_);
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					result = _tmp15_;
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					_g_regex_unref0 (regex);
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					_g_list_free0 (white_collection);
#line 25 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
					return result;
#line 287 "whitelist.c"
				}
#line 20 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
				_g_regex_unref0 (regex);
#line 291 "whitelist.c"
			}
		}
#line 20 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
		_g_list_free0 (white_collection);
#line 296 "whitelist.c"
	}
#line 27 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	result = NULL;
#line 27 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	return result;
#line 302 "whitelist.c"
}


static void adblock_whitelist_class_init (AdblockWhitelistClass * klass) {
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	adblock_whitelist_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/adblock/whitelist.vala"
	ADBLOCK_FEATURE_CLASS (klass)->match = adblock_whitelist_real_match;
#line 311 "whitelist.c"
}


static void adblock_whitelist_instance_init (AdblockWhitelist * self) {
}


GType adblock_whitelist_get_type (void) {
	static volatile gsize adblock_whitelist_type_id__volatile = 0;
	if (g_once_init_enter (&adblock_whitelist_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AdblockWhitelistClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) adblock_whitelist_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AdblockWhitelist), 0, (GInstanceInitFunc) adblock_whitelist_instance_init, NULL };
		GType adblock_whitelist_type_id;
		adblock_whitelist_type_id = g_type_register_static (ADBLOCK_TYPE_FILTER, "AdblockWhitelist", &g_define_type_info, 0);
		g_once_init_leave (&adblock_whitelist_type_id__volatile, adblock_whitelist_type_id);
	}
	return adblock_whitelist_type_id__volatile;
}



