/* devpet.c generated by valac 0.20.1, the Vala compiler
 * generated from devpet.vala, do not modify */

/*
   Copyright (C) 2013 André Stösel <andre@stoesel.de>

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   See the file COPYING for the full license text.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include "midori/midori.h"
#include <glib/gi18n-lib.h>
#include <execinfo.h>


#define DEV_PET_TYPE_TREE_CELLS (dev_pet_tree_cells_get_type ())

#define DEV_PET_TYPE_DATA_WINDOW (dev_pet_data_window_get_type ())
#define DEV_PET_DATA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindow))
#define DEV_PET_DATA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindowClass))
#define DEV_PET_IS_DATA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEV_PET_TYPE_DATA_WINDOW))
#define DEV_PET_IS_DATA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEV_PET_TYPE_DATA_WINDOW))
#define DEV_PET_DATA_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindowClass))

typedef struct _DevPetDataWindow DevPetDataWindow;
typedef struct _DevPetDataWindowClass DevPetDataWindowClass;
typedef struct _DevPetDataWindowPrivate DevPetDataWindowPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define DEV_PET_TYPE_LOG_WINDOW (dev_pet_log_window_get_type ())
#define DEV_PET_LOG_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindow))
#define DEV_PET_LOG_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindowClass))
#define DEV_PET_IS_LOG_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEV_PET_TYPE_LOG_WINDOW))
#define DEV_PET_IS_LOG_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEV_PET_TYPE_LOG_WINDOW))
#define DEV_PET_LOG_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindowClass))

typedef struct _DevPetLogWindow DevPetLogWindow;
typedef struct _DevPetLogWindowClass DevPetLogWindowClass;
typedef struct _DevPetLogWindowPrivate DevPetLogWindowPrivate;

#define DEV_PET_TYPE_MANAGER (dev_pet_manager_get_type ())
#define DEV_PET_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEV_PET_TYPE_MANAGER, DevPetManager))
#define DEV_PET_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEV_PET_TYPE_MANAGER, DevPetManagerClass))
#define DEV_PET_IS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEV_PET_TYPE_MANAGER))
#define DEV_PET_IS_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEV_PET_TYPE_MANAGER))
#define DEV_PET_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEV_PET_TYPE_MANAGER, DevPetManagerClass))

typedef struct _DevPetManager DevPetManager;
typedef struct _DevPetManagerClass DevPetManagerClass;
typedef struct _DevPetManagerPrivate DevPetManagerPrivate;
typedef struct _Block1Data Block1Data;

typedef enum  {
	DEV_PET_TREE_CELLS_MESSAGE,
	DEV_PET_TREE_CELLS_BACKTRACE,
	DEV_PET_TREE_CELLS_STOCK,
	DEV_PET_TREE_CELLS_COUNT
} DevPetTreeCells;

struct _DevPetDataWindow {
	GtkWindow parent_instance;
	DevPetDataWindowPrivate * priv;
};

struct _DevPetDataWindowClass {
	GtkWindowClass parent_class;
};

struct _DevPetDataWindowPrivate {
	gchar* _message;
	gchar* _backtrace;
};

struct _DevPetLogWindow {
	GtkWindow parent_instance;
	DevPetLogWindowPrivate * priv;
};

struct _DevPetLogWindowClass {
	GtkWindowClass parent_class;
};

struct _DevPetLogWindowPrivate {
	DevPetManager* manager;
};

struct _DevPetManager {
	MidoriExtension parent_instance;
	DevPetManagerPrivate * priv;
	GtkListStore* list_store;
};

struct _DevPetManagerClass {
	MidoriExtensionClass parent_class;
};

struct _DevPetManagerPrivate {
	GtkStatusIcon* trayicon;
	DevPetLogWindow* log_window;
	GLogFunc default_log_func;
	gpointer default_log_func_target;
	GDestroyNotify default_log_func_target_destroy_notify;
	GLogLevelFlags icon_flag;
};

struct _Block1Data {
	int _ref_count_;
	DevPetManager * self;
	gint length;
};


extern GtkIconTheme* theme;
GtkIconTheme* theme = NULL;
static gpointer dev_pet_data_window_parent_class = NULL;
static gpointer dev_pet_log_window_parent_class = NULL;
static gpointer dev_pet_manager_parent_class = NULL;

GType dev_pet_tree_cells_get_type (void) G_GNUC_CONST;
GType dev_pet_data_window_get_type (void) G_GNUC_CONST;
#define DEV_PET_DATA_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindowPrivate))
enum  {
	DEV_PET_DATA_WINDOW_DUMMY_PROPERTY,
	DEV_PET_DATA_WINDOW_MESSAGE,
	DEV_PET_DATA_WINDOW_BACKTRACE
};
static void dev_pet_data_window_create_content (DevPetDataWindow* self);
const gchar* dev_pet_data_window_get_message (DevPetDataWindow* self);
const gchar* dev_pet_data_window_get_backtrace (DevPetDataWindow* self);
DevPetDataWindow* dev_pet_data_window_new (const gchar* message, const gchar* backtrace);
DevPetDataWindow* dev_pet_data_window_construct (GType object_type, const gchar* message, const gchar* backtrace);
static void dev_pet_data_window_set_message (DevPetDataWindow* self, const gchar* value);
static void dev_pet_data_window_set_backtrace (DevPetDataWindow* self, const gchar* value);
static void dev_pet_data_window_finalize (GObject* obj);
static void _vala_dev_pet_data_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_dev_pet_data_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType dev_pet_log_window_get_type (void) G_GNUC_CONST;
GType dev_pet_manager_get_type (void) G_GNUC_CONST;
#define DEV_PET_LOG_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindowPrivate))
enum  {
	DEV_PET_LOG_WINDOW_DUMMY_PROPERTY
};
static void dev_pet_log_window_clear_list (DevPetLogWindow* self);
void dev_pet_manager_clear_list (DevPetManager* self);
static void dev_pet_log_window_row_activated (DevPetLogWindow* self, GtkTreePath* path, GtkTreeViewColumn* column);
static void dev_pet_log_window_create_content (DevPetLogWindow* self);
void dev_pet_manager_log_window_closed (DevPetManager* self);
static void _dev_pet_manager_log_window_closed_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void _dev_pet_log_window_clear_list_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _dev_pet_log_window_row_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
DevPetLogWindow* dev_pet_log_window_new (DevPetManager* manager);
DevPetLogWindow* dev_pet_log_window_construct (GType object_type, DevPetManager* manager);
static void dev_pet_log_window_finalize (GObject* obj);
#define DEV_PET_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DEV_PET_TYPE_MANAGER, DevPetManagerPrivate))
enum  {
	DEV_PET_MANAGER_DUMMY_PROPERTY
};
static const gchar* dev_pet_manager_get_stock_from_log_level (DevPetManager* self, GLogLevelFlags flags);
static void dev_pet_manager_ensure_trayicon (DevPetManager* self);
static void dev_pet_manager_show_error_log (DevPetManager* self);
static void _dev_pet_manager_show_error_log_gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self);
static void dev_pet_manager_log_handler (DevPetManager* self, const gchar* domain, GLogLevelFlags flags, const gchar* message);
static void dev_pet_manager_activated (DevPetManager* self, MidoriApp* app);
static void _dev_pet_manager_log_handler_glog_func (const gchar* log_domain, GLogLevelFlags log_levels, const gchar* message, gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gboolean ___lambda2_ (Block1Data* _data1_, GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter);
static gboolean ____lambda2__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self);
static void dev_pet_manager_deactivated (DevPetManager* self);
DevPetManager* dev_pet_manager_new (void);
DevPetManager* dev_pet_manager_construct (GType object_type);
static void _dev_pet_manager_activated_midori_extension_activate (MidoriExtension* _sender, MidoriApp* app, gpointer self);
static void _dev_pet_manager_deactivated_midori_extension_deactivate (MidoriExtension* _sender, gpointer self);
static void dev_pet_manager_finalize (GObject* obj);
MidoriExtension* extension_init (void);


GType dev_pet_tree_cells_get_type (void) {
	static volatile gsize dev_pet_tree_cells_type_id__volatile = 0;
	if (g_once_init_enter (&dev_pet_tree_cells_type_id__volatile)) {
		static const GEnumValue values[] = {{DEV_PET_TREE_CELLS_MESSAGE, "DEV_PET_TREE_CELLS_MESSAGE", "message"}, {DEV_PET_TREE_CELLS_BACKTRACE, "DEV_PET_TREE_CELLS_BACKTRACE", "backtrace"}, {DEV_PET_TREE_CELLS_STOCK, "DEV_PET_TREE_CELLS_STOCK", "stock"}, {DEV_PET_TREE_CELLS_COUNT, "DEV_PET_TREE_CELLS_COUNT", "count"}, {0, NULL, NULL}};
		GType dev_pet_tree_cells_type_id;
		dev_pet_tree_cells_type_id = g_enum_register_static ("DevPetTreeCells", values);
		g_once_init_leave (&dev_pet_tree_cells_type_id__volatile, dev_pet_tree_cells_type_id);
	}
	return dev_pet_tree_cells_type_id__volatile;
}


static void dev_pet_data_window_create_content (DevPetDataWindow* self) {
	const gchar* _tmp0_;
	GtkVBox* _tmp1_;
	GtkVBox* vbox;
	GtkTextBuffer* _tmp2_;
	GtkTextBuffer* message_buffer;
	const gchar* _tmp3_;
	GtkTextView* _tmp4_;
	GtkTextView* message_text_view;
	GtkTextBuffer* _tmp5_;
	GtkTextBuffer* backtrace_buffer;
	const gchar* _tmp6_;
	GtkTextView* _tmp7_;
	GtkTextView* backtrace_text_view;
	GtkScrolledWindow* _tmp8_;
	GtkScrolledWindow* message_scroll;
	GtkScrolledWindow* _tmp9_;
	GtkScrolledWindow* backtrace_scroll;
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->_message;
#line 27 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_window_set_title ((GtkWindow*) self, _tmp0_);
#line 28 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 500, 500);
#line 30 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = (GtkVBox*) gtk_vbox_new (FALSE, 1);
#line 30 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp1_);
#line 30 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	vbox = _tmp1_;
#line 31 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox);
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = gtk_text_buffer_new (NULL);
#line 33 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	message_buffer = _tmp2_;
#line 34 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp3_ = self->priv->_message;
#line 34 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_text_buffer_set_text (message_buffer, _tmp3_, -1);
#line 36 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp4_ = (GtkTextView*) gtk_text_view_new_with_buffer (message_buffer);
#line 36 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp4_);
#line 36 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	message_text_view = _tmp4_;
#line 37 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_text_view_set_editable (message_text_view, FALSE);
#line 39 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp5_ = gtk_text_buffer_new (NULL);
#line 39 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	backtrace_buffer = _tmp5_;
#line 40 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp6_ = self->priv->_backtrace;
#line 40 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_text_buffer_set_text (backtrace_buffer, _tmp6_, -1);
#line 42 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp7_ = (GtkTextView*) gtk_text_view_new_with_buffer (backtrace_buffer);
#line 42 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp7_);
#line 42 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	backtrace_text_view = _tmp7_;
#line 43 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_text_view_set_editable (backtrace_text_view, FALSE);
#line 45 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp8_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 45 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp8_);
#line 45 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	message_scroll = _tmp8_;
#line 46 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_scrolled_window_set_policy (message_scroll, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
#line 47 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) message_scroll, (GtkWidget*) message_text_view);
#line 49 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp9_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 49 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp9_);
#line 49 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	backtrace_scroll = _tmp9_;
#line 50 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_scrolled_window_set_policy (backtrace_scroll, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
#line 51 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) backtrace_scroll, (GtkWidget*) backtrace_text_view);
#line 53 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) message_scroll, FALSE, FALSE, (guint) 0);
#line 54 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_box_pack_end ((GtkBox*) vbox, (GtkWidget*) backtrace_scroll, TRUE, TRUE, (guint) 0);
#line 56 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (backtrace_scroll);
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (message_scroll);
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (backtrace_text_view);
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (backtrace_buffer);
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (message_text_view);
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (message_buffer);
#line 26 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (vbox);
#line 307 "devpet.c"
}


DevPetDataWindow* dev_pet_data_window_construct (GType object_type, const gchar* message, const gchar* backtrace) {
	DevPetDataWindow * self = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (message != NULL, NULL);
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (backtrace != NULL, NULL);
#line 60 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = message;
#line 60 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = backtrace;
#line 60 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self = (DevPetDataWindow*) g_object_new (object_type, "type", GTK_WINDOW_TOPLEVEL, "window-position", GTK_WIN_POS_CENTER, "message", _tmp0_, "backtrace", _tmp1_, NULL);
#line 65 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_data_window_create_content (self);
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return self;
#line 329 "devpet.c"
}


DevPetDataWindow* dev_pet_data_window_new (const gchar* message, const gchar* backtrace) {
#line 59 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return dev_pet_data_window_construct (DEV_PET_TYPE_DATA_WINDOW, message, backtrace);
#line 336 "devpet.c"
}


const gchar* dev_pet_data_window_get_message (DevPetDataWindow* self) {
	const gchar* result;
	const gchar* _tmp0_;
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->_message;
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	result = _tmp0_;
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return result;
#line 351 "devpet.c"
}


static void dev_pet_data_window_set_message (DevPetDataWindow* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = value;
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_free0 (self->priv->_message);
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->_message = _tmp1_;
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_notify ((GObject *) self, "message");
#line 370 "devpet.c"
}


const gchar* dev_pet_data_window_get_backtrace (DevPetDataWindow* self) {
	const gchar* result;
	const gchar* _tmp0_;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->_backtrace;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	result = _tmp0_;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return result;
#line 385 "devpet.c"
}


static void dev_pet_data_window_set_backtrace (DevPetDataWindow* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = value;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_free0 (self->priv->_backtrace);
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->_backtrace = _tmp1_;
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_notify ((GObject *) self, "backtrace");
#line 404 "devpet.c"
}


static void dev_pet_data_window_class_init (DevPetDataWindowClass * klass) {
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_data_window_parent_class = g_type_class_peek_parent (klass);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_type_class_add_private (klass, sizeof (DevPetDataWindowPrivate));
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_dev_pet_data_window_get_property;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_dev_pet_data_window_set_property;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->finalize = dev_pet_data_window_finalize;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), DEV_PET_DATA_WINDOW_MESSAGE, g_param_spec_string ("message", "message", "message", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), DEV_PET_DATA_WINDOW_BACKTRACE, g_param_spec_string ("backtrace", "backtrace", "backtrace", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 423 "devpet.c"
}


static void dev_pet_data_window_instance_init (DevPetDataWindow * self) {
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv = DEV_PET_DATA_WINDOW_GET_PRIVATE (self);
#line 430 "devpet.c"
}


static void dev_pet_data_window_finalize (GObject* obj) {
	DevPetDataWindow * self;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindow);
#line 23 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_free0 (self->priv->_message);
#line 24 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_free0 (self->priv->_backtrace);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (dev_pet_data_window_parent_class)->finalize (obj);
#line 444 "devpet.c"
}


GType dev_pet_data_window_get_type (void) {
	static volatile gsize dev_pet_data_window_type_id__volatile = 0;
	if (g_once_init_enter (&dev_pet_data_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DevPetDataWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dev_pet_data_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DevPetDataWindow), 0, (GInstanceInitFunc) dev_pet_data_window_instance_init, NULL };
		GType dev_pet_data_window_type_id;
		dev_pet_data_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "DevPetDataWindow", &g_define_type_info, 0);
		g_once_init_leave (&dev_pet_data_window_type_id__volatile, dev_pet_data_window_type_id);
	}
	return dev_pet_data_window_type_id__volatile;
}


static void _vala_dev_pet_data_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DevPetDataWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindow);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	switch (property_id) {
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		case DEV_PET_DATA_WINDOW_MESSAGE:
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		g_value_set_string (value, dev_pet_data_window_get_message (self));
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		break;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		case DEV_PET_DATA_WINDOW_BACKTRACE:
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		g_value_set_string (value, dev_pet_data_window_get_backtrace (self));
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		break;
#line 477 "devpet.c"
		default:
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		break;
#line 483 "devpet.c"
	}
}


static void _vala_dev_pet_data_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DevPetDataWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindow);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	switch (property_id) {
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		case DEV_PET_DATA_WINDOW_MESSAGE:
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		dev_pet_data_window_set_message (self, g_value_get_string (value));
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		break;
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		case DEV_PET_DATA_WINDOW_BACKTRACE:
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		dev_pet_data_window_set_backtrace (self, g_value_get_string (value));
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		break;
#line 505 "devpet.c"
		default:
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 22 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		break;
#line 511 "devpet.c"
	}
}


static void dev_pet_log_window_clear_list (DevPetLogWindow* self) {
	DevPetManager* _tmp0_;
#line 72 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->manager;
#line 73 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_manager_clear_list (_tmp0_);
#line 74 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 526 "devpet.c"
}


static void dev_pet_log_window_row_activated (DevPetLogWindow* self, GtkTreePath* path, GtkTreeViewColumn* column) {
	GtkTreeIter iter = {0};
	DevPetManager* _tmp0_;
	GtkListStore* _tmp1_;
	GtkTreePath* _tmp2_;
	GtkTreeIter _tmp3_ = {0};
	gboolean _tmp4_ = FALSE;
#line 78 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 78 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (path != NULL);
#line 78 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (column != NULL);
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->manager;
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = _tmp0_->list_store;
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = path;
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp4_ = gtk_tree_model_get_iter ((GtkTreeModel*) _tmp1_, &_tmp3_, _tmp2_);
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	iter = _tmp3_;
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp4_) {
#line 555 "devpet.c"
		gchar* message = NULL;
		gchar* backtrace = NULL;
		DevPetManager* _tmp5_;
		GtkListStore* _tmp6_;
		GtkTreeIter _tmp7_;
		const gchar* _tmp8_;
		const gchar* _tmp9_;
		DevPetDataWindow* _tmp10_;
		DevPetDataWindow* data_window;
		DevPetDataWindow* _tmp11_;
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp5_ = self->priv->manager;
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp6_ = _tmp5_->list_store;
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp7_ = iter;
#line 83 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		gtk_tree_model_get ((GtkTreeModel*) _tmp6_, &_tmp7_, DEV_PET_TREE_CELLS_MESSAGE, &message, DEV_PET_TREE_CELLS_BACKTRACE, &backtrace, -1, -1);
#line 87 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp8_ = message;
#line 87 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp9_ = backtrace;
#line 87 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp10_ = dev_pet_data_window_new (_tmp8_, _tmp9_);
#line 87 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		g_object_ref_sink (_tmp10_);
#line 87 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		data_window = _tmp10_;
#line 88 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp11_ = data_window;
#line 88 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		gtk_widget_show ((GtkWidget*) _tmp11_);
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_g_object_unref0 (data_window);
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_g_free0 (backtrace);
#line 80 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_g_free0 (message);
#line 594 "devpet.c"
	}
}


static void _dev_pet_manager_log_window_closed_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_manager_log_window_closed (self);
#line 602 "devpet.c"
}


static void _dev_pet_log_window_clear_list_gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 112 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_log_window_clear_list (self);
#line 609 "devpet.c"
}


static void _dev_pet_log_window_row_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
#line 129 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_log_window_row_activated (self, path, column);
#line 616 "devpet.c"
}


static void dev_pet_log_window_create_content (DevPetLogWindow* self) {
	DevPetManager* _tmp0_;
	GtkVBox* _tmp1_;
	GtkVBox* vbox;
	const gchar* _tmp2_ = NULL;
	GtkLabel* _tmp3_;
	GtkLabel* label;
	GtkScrolledWindow* _tmp4_;
	GtkScrolledWindow* scroll_windows;
	GtkButton* _tmp5_;
	GtkButton* clear;
	DevPetManager* _tmp6_;
	GtkListStore* _tmp7_;
	GtkTreeView* _tmp8_;
	GtkTreeView* treeview;
	GtkCellRendererPixbuf* _tmp9_;
	GtkCellRendererPixbuf* _tmp10_;
	GtkCellRendererText* _tmp11_;
	GtkCellRendererText* _tmp12_;
#line 93 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 94 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_window_set_title ((GtkWindow*) self, "Midori - DevPet");
#line 95 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 500, 250);
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->manager;
#line 96 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_signal_connect_object ((GtkWidget*) self, "destroy", (GCallback) _dev_pet_manager_log_window_closed_gtk_widget_destroy, _tmp0_, 0);
#line 98 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = (GtkVBox*) gtk_vbox_new (FALSE, 1);
#line 98 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp1_);
#line 98 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	vbox = _tmp1_;
#line 99 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox);
#line 102 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = _ ("Double click for more information");
#line 102 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp3_ = (GtkLabel*) gtk_label_new (_tmp2_);
#line 102 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp3_);
#line 102 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	label = _tmp3_;
#line 103 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) label, FALSE, FALSE, (guint) 0);
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp4_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp4_);
#line 106 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	scroll_windows = _tmp4_;
#line 107 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_scrolled_window_set_policy (scroll_windows, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
#line 108 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_scrolled_window_set_shadow_type (scroll_windows, GTK_SHADOW_ETCHED_IN);
#line 111 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp5_ = (GtkButton*) gtk_button_new_from_stock ("gtk-clear");
#line 111 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp5_);
#line 111 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	clear = _tmp5_;
#line 112 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_signal_connect_object (clear, "clicked", (GCallback) _dev_pet_log_window_clear_list_gtk_button_clicked, self, 0);
#line 114 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) scroll_windows, TRUE, TRUE, (guint) 0);
#line 115 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) clear, FALSE, FALSE, (guint) 0);
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp6_ = self->priv->manager;
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp7_ = _tmp6_->list_store;
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp8_ = (GtkTreeView*) gtk_tree_view_new_with_model ((GtkTreeModel*) _tmp7_);
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp8_);
#line 118 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	treeview = _tmp8_;
#line 119 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) scroll_windows, (GtkWidget*) treeview);
#line 121 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp9_ = (GtkCellRendererPixbuf*) gtk_cell_renderer_pixbuf_new ();
#line 121 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp9_);
#line 121 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp10_ = _tmp9_;
#line 121 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_tree_view_insert_column_with_attributes (treeview, -1, "Type", (GtkCellRenderer*) _tmp10_, "stock-id", DEV_PET_TREE_CELLS_STOCK, NULL);
#line 121 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (_tmp10_);
#line 124 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp11_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 124 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp11_);
#line 124 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp12_ = _tmp11_;
#line 124 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_tree_view_insert_column_with_attributes (treeview, -1, "Message", (GtkCellRenderer*) _tmp12_, "text", DEV_PET_TREE_CELLS_MESSAGE, NULL);
#line 124 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (_tmp12_);
#line 129 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_signal_connect_object (treeview, "row-activated", (GCallback) _dev_pet_log_window_row_activated_gtk_tree_view_row_activated, self, 0);
#line 132 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 93 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (treeview);
#line 93 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (clear);
#line 93 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (scroll_windows);
#line 93 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (label);
#line 93 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (vbox);
#line 735 "devpet.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return self ? g_object_ref (self) : NULL;
#line 742 "devpet.c"
}


DevPetLogWindow* dev_pet_log_window_construct (GType object_type, DevPetManager* manager) {
	DevPetLogWindow * self = NULL;
	DevPetManager* _tmp0_;
	DevPetManager* _tmp1_;
#line 135 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (manager != NULL, NULL);
#line 136 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self = (DevPetLogWindow*) g_object_new (object_type, "type", GTK_WINDOW_TOPLEVEL, "window-position", GTK_WIN_POS_CENTER, NULL);
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = manager;
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->manager);
#line 139 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->manager = _tmp1_;
#line 140 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_log_window_create_content (self);
#line 135 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return self;
#line 766 "devpet.c"
}


DevPetLogWindow* dev_pet_log_window_new (DevPetManager* manager) {
#line 135 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return dev_pet_log_window_construct (DEV_PET_TYPE_LOG_WINDOW, manager);
#line 773 "devpet.c"
}


static void dev_pet_log_window_class_init (DevPetLogWindowClass * klass) {
#line 69 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_log_window_parent_class = g_type_class_peek_parent (klass);
#line 69 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_type_class_add_private (klass, sizeof (DevPetLogWindowPrivate));
#line 69 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->finalize = dev_pet_log_window_finalize;
#line 784 "devpet.c"
}


static void dev_pet_log_window_instance_init (DevPetLogWindow * self) {
#line 69 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv = DEV_PET_LOG_WINDOW_GET_PRIVATE (self);
#line 791 "devpet.c"
}


static void dev_pet_log_window_finalize (GObject* obj) {
	DevPetLogWindow * self;
#line 69 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindow);
#line 70 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->manager);
#line 69 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (dev_pet_log_window_parent_class)->finalize (obj);
#line 803 "devpet.c"
}


GType dev_pet_log_window_get_type (void) {
	static volatile gsize dev_pet_log_window_type_id__volatile = 0;
	if (g_once_init_enter (&dev_pet_log_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DevPetLogWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dev_pet_log_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DevPetLogWindow), 0, (GInstanceInitFunc) dev_pet_log_window_instance_init, NULL };
		GType dev_pet_log_window_type_id;
		dev_pet_log_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "DevPetLogWindow", &g_define_type_info, 0);
		g_once_init_leave (&dev_pet_log_window_type_id__volatile, dev_pet_log_window_type_id);
	}
	return dev_pet_log_window_type_id__volatile;
}


void dev_pet_manager_clear_list (DevPetManager* self) {
	GtkStatusIcon* _tmp0_;
	GtkListStore* _tmp2_;
#line 151 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 152 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->icon_flag = G_LOG_LEVEL_DEBUG;
#line 153 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->trayicon;
#line 153 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp0_ != NULL) {
#line 830 "devpet.c"
		GtkStatusIcon* _tmp1_;
#line 154 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp1_ = self->priv->trayicon;
#line 154 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		gtk_status_icon_set_visible (_tmp1_, FALSE);
#line 836 "devpet.c"
	}
#line 155 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = self->list_store;
#line 155 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_list_store_clear (_tmp2_);
#line 842 "devpet.c"
}


void dev_pet_manager_log_window_closed (DevPetManager* self) {
#line 158 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 159 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->log_window);
#line 159 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->log_window = NULL;
#line 853 "devpet.c"
}


static const gchar* dev_pet_manager_get_stock_from_log_level (DevPetManager* self, GLogLevelFlags flags) {
	const gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	GLogLevelFlags _tmp1_;
	GLogLevelFlags _tmp2_;
	gboolean _tmp5_;
#line 162 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = flags;
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = flags;
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if ((_tmp1_ & G_LOG_LEVEL_CRITICAL) == _tmp2_) {
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp0_ = TRUE;
#line 873 "devpet.c"
	} else {
		GLogLevelFlags _tmp3_;
		GLogLevelFlags _tmp4_;
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp3_ = flags;
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp4_ = flags;
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp0_ = (_tmp3_ & G_LOG_LEVEL_ERROR) == _tmp4_;
#line 883 "devpet.c"
	}
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp5_ = _tmp0_;
#line 163 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp5_) {
#line 164 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		result = GTK_STOCK_DIALOG_ERROR;
#line 164 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		return result;
#line 893 "devpet.c"
	} else {
		GLogLevelFlags _tmp6_;
		GLogLevelFlags _tmp7_;
#line 165 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp6_ = flags;
#line 165 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp7_ = flags;
#line 165 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		if ((_tmp6_ & G_LOG_LEVEL_WARNING) == _tmp7_) {
#line 166 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			result = GTK_STOCK_DIALOG_WARNING;
#line 166 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			return result;
#line 907 "devpet.c"
		}
	}
#line 168 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	result = GTK_STOCK_DIALOG_INFO;
#line 168 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return result;
#line 914 "devpet.c"
}


static void _dev_pet_manager_show_error_log_gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self) {
#line 177 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_manager_show_error_log (self);
#line 921 "devpet.c"
}


static void dev_pet_manager_ensure_trayicon (DevPetManager* self) {
	GtkStatusIcon* _tmp0_;
	GtkStatusIcon* _tmp1_;
	GtkStatusIcon* _tmp2_;
	GtkStatusIcon* _tmp3_;
#line 171 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 172 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->trayicon;
#line 172 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp0_ != NULL) {
#line 173 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		return;
#line 938 "devpet.c"
	}
#line 175 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = gtk_status_icon_new ();
#line 175 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->trayicon);
#line 175 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->trayicon = _tmp1_;
#line 176 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = self->priv->trayicon;
#line 176 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_status_icon_set_tooltip_text (_tmp2_, "Midori - DevPet");
#line 177 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp3_ = self->priv->trayicon;
#line 177 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_signal_connect_object (_tmp3_, "activate", (GCallback) _dev_pet_manager_show_error_log_gtk_status_icon_activate, self, 0);
#line 954 "devpet.c"
}


static void dev_pet_manager_log_handler (DevPetManager* self, const gchar* domain, GLogLevelFlags flags, const gchar* message) {
	GtkTreeIter iter = {0};
	GLogLevelFlags _tmp0_;
	const gchar* _tmp1_ = NULL;
	const gchar* stock;
	GLogLevelFlags _tmp2_;
	GLogLevelFlags _tmp3_;
	gchar* _tmp7_;
	gchar* bt;
	void* buffer[100] = {0};
	gint _tmp8_ = 0;
	gint num;
	gint _tmp9_;
	gchar** _tmp10_ = NULL;
	gchar** symbols;
	gint symbols_length1;
	gint _symbols_size_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	GtkListStore* _tmp24_;
	GtkTreeIter _tmp25_ = {0};
	GtkListStore* _tmp26_;
	GtkTreeIter _tmp27_;
	const gchar* _tmp28_;
	const gchar* _tmp29_;
	const gchar* _tmp30_;
	GtkStatusIcon* _tmp31_;
#line 180 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 180 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (message != NULL);
#line 182 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = flags;
#line 182 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = dev_pet_manager_get_stock_from_log_level (self, _tmp0_);
#line 182 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	stock = _tmp1_;
#line 184 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_manager_ensure_trayicon (self);
#line 186 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = flags;
#line 186 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp3_ = self->priv->icon_flag;
#line 186 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp2_ < _tmp3_) {
#line 1003 "devpet.c"
		GLogLevelFlags _tmp4_;
		GtkStatusIcon* _tmp5_;
		const gchar* _tmp6_;
#line 187 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp4_ = flags;
#line 187 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		self->priv->icon_flag = _tmp4_;
#line 188 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp5_ = self->priv->trayicon;
#line 188 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp6_ = stock;
#line 188 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		gtk_status_icon_set_from_stock (_tmp5_, _tmp6_);
#line 1017 "devpet.c"
	}
#line 192 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp7_ = g_strdup ("");
#line 192 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	bt = _tmp7_;
#line 194 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp8_ = backtrace (buffer, 100);
#line 194 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	num = _tmp8_;
#line 196 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp9_ = num;
#line 196 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp10_ = backtrace_symbols (buffer, _tmp9_);
#line 196 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	symbols = _tmp10_;
#line 196 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	symbols_length1 = -1;
#line 196 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_symbols_size_ = symbols_length1;
#line 197 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp11_ = symbols;
#line 197 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp11__length1 = symbols_length1;
#line 197 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp11_ != NULL) {
#line 1043 "devpet.c"
		{
			gint i;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			i = 3;
#line 1048 "devpet.c"
			{
				gboolean _tmp12_;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
				_tmp12_ = TRUE;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
				while (TRUE) {
#line 1055 "devpet.c"
					gboolean _tmp13_;
					gint _tmp15_;
					gint _tmp16_;
					const gchar* _tmp17_;
					gchar** _tmp18_;
					gint _tmp18__length1;
					gint _tmp19_;
					const gchar* _tmp20_;
					gchar* _tmp21_ = NULL;
					gchar* _tmp22_;
					gchar* _tmp23_;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp13_ = _tmp12_;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					if (!_tmp13_) {
#line 1071 "devpet.c"
						gint _tmp14_;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
						_tmp14_ = i;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
						i = _tmp14_ + 1;
#line 1077 "devpet.c"
					}
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp12_ = FALSE;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp15_ = i;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp16_ = num;
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					if (!(_tmp15_ < _tmp16_)) {
#line 199 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
						break;
#line 1089 "devpet.c"
					}
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp17_ = bt;
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp18_ = symbols;
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp18__length1 = symbols_length1;
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp19_ = i;
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp20_ = _tmp18_[_tmp19_];
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp21_ = g_strdup_printf ("\r\n%s", _tmp20_);
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp22_ = _tmp21_;
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_tmp23_ = g_strconcat (_tmp17_, _tmp22_, NULL);
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_g_free0 (bt);
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					bt = _tmp23_;
#line 200 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
					_g_free0 (_tmp22_);
#line 1113 "devpet.c"
				}
			}
		}
	}
#line 205 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp24_ = self->list_store;
#line 205 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_list_store_append (_tmp24_, &_tmp25_);
#line 205 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	iter = _tmp25_;
#line 206 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp26_ = self->list_store;
#line 206 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp27_ = iter;
#line 206 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp28_ = message;
#line 206 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp29_ = bt;
#line 206 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp30_ = stock;
#line 206 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_list_store_set (_tmp26_, &_tmp27_, DEV_PET_TREE_CELLS_MESSAGE, _tmp28_, DEV_PET_TREE_CELLS_BACKTRACE, _tmp29_, DEV_PET_TREE_CELLS_STOCK, _tmp30_, -1);
#line 213 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp31_ = self->priv->trayicon;
#line 213 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	gtk_status_icon_set_visible (_tmp31_, TRUE);
#line 180 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_free0 (bt);
#line 1142 "devpet.c"
}


static void dev_pet_manager_show_error_log (DevPetManager* self) {
	DevPetLogWindow* _tmp0_;
#line 216 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 217 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->log_window;
#line 217 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp0_ == NULL) {
#line 1154 "devpet.c"
		DevPetLogWindow* _tmp1_;
		DevPetLogWindow* _tmp2_;
#line 218 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp1_ = dev_pet_log_window_new (self);
#line 218 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		g_object_ref_sink (_tmp1_);
#line 218 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_g_object_unref0 (self->priv->log_window);
#line 218 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		self->priv->log_window = _tmp1_;
#line 219 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp2_ = self->priv->log_window;
#line 219 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		gtk_widget_show ((GtkWidget*) _tmp2_);
#line 1169 "devpet.c"
	} else {
		DevPetLogWindow* _tmp3_;
		gboolean _tmp4_ = FALSE;
		gboolean _tmp5_;
#line 221 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp3_ = self->priv->log_window;
#line 221 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		g_object_get ((GtkWindow*) _tmp3_, "is-active", &_tmp4_, NULL);
#line 221 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp5_ = _tmp4_;
#line 221 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		if (_tmp5_) {
#line 1182 "devpet.c"
			DevPetLogWindow* _tmp6_;
#line 222 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			_tmp6_ = self->priv->log_window;
#line 222 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			gtk_widget_hide ((GtkWidget*) _tmp6_);
#line 1188 "devpet.c"
		} else {
			DevPetLogWindow* _tmp7_;
#line 224 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			_tmp7_ = self->priv->log_window;
#line 224 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			gtk_window_present ((GtkWindow*) _tmp7_);
#line 1195 "devpet.c"
		}
	}
}


static void _dev_pet_manager_log_handler_glog_func (const gchar* log_domain, GLogLevelFlags log_levels, const gchar* message, gpointer self) {
#line 231 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_manager_log_handler (self, log_domain, log_levels, message);
#line 1204 "devpet.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return _data1_;
#line 1213 "devpet.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 1222 "devpet.c"
		DevPetManager * self;
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		self = _data1_->self;
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_g_object_unref0 (self);
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		g_slice_free (Block1Data, _data1_);
#line 1230 "devpet.c"
	}
}


static gboolean ___lambda2_ (Block1Data* _data1_, GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter) {
	DevPetManager * self;
	gboolean result = FALSE;
	gint _tmp0_;
#line 234 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self = _data1_->self;
#line 234 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (model != NULL, FALSE);
#line 234 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (path != NULL, FALSE);
#line 234 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_val_if_fail (iter != NULL, FALSE);
#line 235 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = _data1_->length;
#line 235 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_data1_->length = _tmp0_ + 1;
#line 236 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	result = FALSE;
#line 236 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return result;
#line 1255 "devpet.c"
}


static gboolean ____lambda2__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self) {
	gboolean result;
	result = ___lambda2_ (self, model, path, iter);
#line 234 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return result;
#line 1264 "devpet.c"
}


static void dev_pet_manager_activated (DevPetManager* self, MidoriApp* app) {
	GLogFunc _tmp0_;
	void* _tmp0__target;
	GtkStatusIcon* _tmp1_;
#line 229 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 229 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (app != NULL);
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = g_log_default_handler;
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0__target = NULL;
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	(self->priv->default_log_func_target_destroy_notify == NULL) ? NULL : (self->priv->default_log_func_target_destroy_notify (self->priv->default_log_func_target), NULL);
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func = NULL;
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func_target = NULL;
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func_target_destroy_notify = NULL;
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func = _tmp0_;
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func_target = _tmp0__target;
#line 230 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func_target_destroy_notify = NULL;
#line 231 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_log_set_default_handler (_dev_pet_manager_log_handler_glog_func, self);
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = self->priv->trayicon;
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp1_ != NULL) {
#line 1300 "devpet.c"
		Block1Data* _data1_;
		GtkListStore* _tmp2_;
		gint _tmp3_;
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_data1_ = g_slice_new0 (Block1Data);
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_data1_->_ref_count_ = 1;
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_data1_->self = g_object_ref (self);
#line 233 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_data1_->length = 0;
#line 234 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp2_ = self->list_store;
#line 234 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		gtk_tree_model_foreach ((GtkTreeModel*) _tmp2_, ____lambda2__gtk_tree_model_foreach_func, _data1_);
#line 239 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp3_ = _data1_->length;
#line 239 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		if (_tmp3_ > 0) {
#line 1320 "devpet.c"
			GtkStatusIcon* _tmp4_;
#line 240 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			_tmp4_ = self->priv->trayicon;
#line 240 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
			gtk_status_icon_set_visible (_tmp4_, TRUE);
#line 1326 "devpet.c"
		}
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		block1_data_unref (_data1_);
#line 232 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_data1_ = NULL;
#line 1332 "devpet.c"
	}
}


static void dev_pet_manager_deactivated (DevPetManager* self) {
	GtkStatusIcon* _tmp0_;
	GLogFunc _tmp2_;
	void* _tmp2__target;
#line 245 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 246 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->trayicon;
#line 246 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	if (_tmp0_ != NULL) {
#line 1347 "devpet.c"
		GtkStatusIcon* _tmp1_;
#line 247 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		_tmp1_ = self->priv->trayicon;
#line 247 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
		gtk_status_icon_set_visible (_tmp1_, FALSE);
#line 1353 "devpet.c"
	}
#line 249 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = self->priv->default_log_func;
#line 249 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2__target = self->priv->default_log_func_target;
#line 249 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_log_set_default_handler (_tmp2_, _tmp2__target);
#line 1361 "devpet.c"
}


static void _dev_pet_manager_activated_midori_extension_activate (MidoriExtension* _sender, MidoriApp* app, gpointer self) {
#line 260 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_manager_activated (self, app);
#line 1368 "devpet.c"
}


static void _dev_pet_manager_deactivated_midori_extension_deactivate (MidoriExtension* _sender, gpointer self) {
#line 261 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_manager_deactivated (self);
#line 1375 "devpet.c"
}


DevPetManager* dev_pet_manager_construct (GType object_type) {
	DevPetManager * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkListStore* _tmp2_;
#line 253 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = _ ("DevPet");
#line 253 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = _ ("This extension shows glib error messages in systray.");
#line 253 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self = (DevPetManager*) g_object_new (object_type, "name", _tmp0_, "description", _tmp1_, "version", "0.1", "authors", "André Stösel <andre@stoesel.de>", NULL);
#line 258 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = gtk_list_store_new ((gint) DEV_PET_TREE_CELLS_COUNT, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);
#line 258 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (self->list_store);
#line 258 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->list_store = _tmp2_;
#line 260 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_signal_connect_object ((MidoriExtension*) self, "activate", (GCallback) _dev_pet_manager_activated_midori_extension_activate, self, 0);
#line 261 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_signal_connect_object ((MidoriExtension*) self, "deactivate", (GCallback) _dev_pet_manager_deactivated_midori_extension_deactivate, self, 0);
#line 252 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return self;
#line 1402 "devpet.c"
}


DevPetManager* dev_pet_manager_new (void) {
#line 252 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return dev_pet_manager_construct (DEV_PET_TYPE_MANAGER);
#line 1409 "devpet.c"
}


static void dev_pet_manager_class_init (DevPetManagerClass * klass) {
#line 144 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	dev_pet_manager_parent_class = g_type_class_peek_parent (klass);
#line 144 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	g_type_class_add_private (klass, sizeof (DevPetManagerPrivate));
#line 144 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->finalize = dev_pet_manager_finalize;
#line 1420 "devpet.c"
}


static void dev_pet_manager_instance_init (DevPetManager * self) {
#line 144 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv = DEV_PET_MANAGER_GET_PRIVATE (self);
#line 146 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->trayicon = NULL;
#line 149 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->icon_flag = G_LOG_LEVEL_DEBUG;
#line 1431 "devpet.c"
}


static void dev_pet_manager_finalize (GObject* obj) {
	DevPetManager * self;
#line 144 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DEV_PET_TYPE_MANAGER, DevPetManager);
#line 145 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (self->list_store);
#line 146 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->trayicon);
#line 147 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->log_window);
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	(self->priv->default_log_func_target_destroy_notify == NULL) ? NULL : (self->priv->default_log_func_target_destroy_notify (self->priv->default_log_func_target), NULL);
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func = NULL;
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func_target = NULL;
#line 148 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	self->priv->default_log_func_target_destroy_notify = NULL;
#line 144 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (dev_pet_manager_parent_class)->finalize (obj);
#line 1455 "devpet.c"
}


GType dev_pet_manager_get_type (void) {
	static volatile gsize dev_pet_manager_type_id__volatile = 0;
	if (g_once_init_enter (&dev_pet_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DevPetManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dev_pet_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DevPetManager), 0, (GInstanceInitFunc) dev_pet_manager_instance_init, NULL };
		GType dev_pet_manager_type_id;
		dev_pet_manager_type_id = g_type_register_static (MIDORI_TYPE_EXTENSION, "DevPetManager", &g_define_type_info, 0);
		g_once_init_leave (&dev_pet_manager_type_id__volatile, dev_pet_manager_type_id);
	}
	return dev_pet_manager_type_id__volatile;
}


MidoriExtension* extension_init (void) {
	MidoriExtension* result = NULL;
	GtkIconTheme* _tmp0_ = NULL;
	GtkIconTheme* _tmp1_;
	DevPetManager* _tmp2_;
#line 267 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp0_ = gtk_icon_theme_get_default ();
#line 267 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 267 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_g_object_unref0 (theme);
#line 267 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	theme = _tmp1_;
#line 268 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	_tmp2_ = dev_pet_manager_new ();
#line 268 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	result = (MidoriExtension*) _tmp2_;
#line 268 "/home/zrl/epiphany_webkit/Webkit2Browser/Source/midori/extensions/devpet.vala"
	return result;
#line 1490 "devpet.c"
}



