/* domain-keys.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __DOMAIN_KEYS_H__
#define __DOMAIN_KEYS_H__

#include <glib.h>
#include "midori/midori.h"

G_BEGIN_DECLS



MidoriExtension* extension_init (void);


G_END_DECLS

#endif
