/* history-list.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __HISTORY_LIST_H__
#define __HISTORY_LIST_H__

#include <glib.h>
#include "midori/midori.h"

G_BEGIN_DECLS



MidoriExtension* extension_init (void);


G_END_DECLS

#endif
