/* webmedia-now-playing.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __WEBMEDIA_NOW_PLAYING_H__
#define __WEBMEDIA_NOW_PLAYING_H__

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include "midori/midori.h"

G_BEGIN_DECLS


#define SANDCAT_TYPE_DBUS_SERVICE (sandcat_dbus_service_get_type ())
#define SANDCAT_DBUS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SANDCAT_TYPE_DBUS_SERVICE, SandcatDbusService))
#define SANDCAT_DBUS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SANDCAT_TYPE_DBUS_SERVICE, SandcatDbusServiceClass))
#define SANDCAT_IS_DBUS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SANDCAT_TYPE_DBUS_SERVICE))
#define SANDCAT_IS_DBUS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SANDCAT_TYPE_DBUS_SERVICE))
#define SANDCAT_DBUS_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SANDCAT_TYPE_DBUS_SERVICE, SandcatDbusServiceClass))

typedef struct _SandcatDbusService SandcatDbusService;
typedef struct _SandcatDbusServiceClass SandcatDbusServiceClass;
typedef struct _SandcatDbusServicePrivate SandcatDbusServicePrivate;

#define SANDCAT_TYPE_WEB_MEDIA_NOTIFY (sandcat_web_media_notify_get_type ())
#define SANDCAT_WEB_MEDIA_NOTIFY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SANDCAT_TYPE_WEB_MEDIA_NOTIFY, SandcatWebMediaNotify))
#define SANDCAT_WEB_MEDIA_NOTIFY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SANDCAT_TYPE_WEB_MEDIA_NOTIFY, SandcatWebMediaNotifyClass))
#define SANDCAT_IS_WEB_MEDIA_NOTIFY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SANDCAT_TYPE_WEB_MEDIA_NOTIFY))
#define SANDCAT_IS_WEB_MEDIA_NOTIFY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SANDCAT_TYPE_WEB_MEDIA_NOTIFY))
#define SANDCAT_WEB_MEDIA_NOTIFY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SANDCAT_TYPE_WEB_MEDIA_NOTIFY, SandcatWebMediaNotifyClass))

typedef struct _SandcatWebMediaNotify SandcatWebMediaNotify;
typedef struct _SandcatWebMediaNotifyClass SandcatWebMediaNotifyClass;
typedef struct _SandcatWebMediaNotifyPrivate SandcatWebMediaNotifyPrivate;

struct _SandcatDbusService {
	GObject parent_instance;
	SandcatDbusServicePrivate * priv;
};

struct _SandcatDbusServiceClass {
	GObjectClass parent_class;
};

struct _SandcatWebMediaNotify {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SandcatWebMediaNotifyPrivate * priv;
};

struct _SandcatWebMediaNotifyClass {
	GTypeClass parent_class;
	void (*finalize) (SandcatWebMediaNotify *self);
};


GType sandcat_dbus_service_get_type (void) G_GNUC_CONST;
guint sandcat_dbus_service_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
SandcatDbusService* sandcat_dbus_service_new (void);
SandcatDbusService* sandcat_dbus_service_construct (GType object_type);
void sandcat_dbus_service_dbus_empty (SandcatDbusService* self);
void sandcat_dbus_service_register_service (SandcatDbusService* self);
void sandcat_dbus_service_unregister_service (SandcatDbusService* self);
const gchar* sandcat_dbus_service_get_video_title (SandcatDbusService* self);
void sandcat_dbus_service_set_video_title (SandcatDbusService* self, const gchar* value);
const gchar* sandcat_dbus_service_get_video_uri (SandcatDbusService* self);
void sandcat_dbus_service_set_video_uri (SandcatDbusService* self, const gchar* value);
gpointer sandcat_web_media_notify_ref (gpointer instance);
void sandcat_web_media_notify_unref (gpointer instance);
GParamSpec* sandcat_param_spec_web_media_notify (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sandcat_value_set_web_media_notify (GValue* value, gpointer v_object);
void sandcat_value_take_web_media_notify (GValue* value, gpointer v_object);
gpointer sandcat_value_get_web_media_notify (const GValue* value);
GType sandcat_web_media_notify_get_type (void) G_GNUC_CONST;
void sandcat_web_media_notify_show_notify (SandcatWebMediaNotify* self);
SandcatWebMediaNotify* sandcat_web_media_notify_new (void);
SandcatWebMediaNotify* sandcat_web_media_notify_construct (GType object_type);
const gchar* sandcat_web_media_notify_get_notify_video_title (SandcatWebMediaNotify* self);
void sandcat_web_media_notify_set_notify_video_title (SandcatWebMediaNotify* self, const gchar* value);
const gchar* sandcat_web_media_notify_get_notify_media (SandcatWebMediaNotify* self);
void sandcat_web_media_notify_set_notify_media (SandcatWebMediaNotify* self, const gchar* value);
MidoriExtension* extension_init (void);


G_END_DECLS

#endif
